### PR TITLE
Double linked list

### LINKED ISSUE #172: Double linked list
# Aim

- Creating a double linked list

# Details

- Doubly linked list is a type of linked list in which each node apart from storing its data has two links. The first link points to the previous node in the list and the second link points to the next node in the list. The first node of the list has its previous link pointing to NULL similarly the last node of the list has its next node pointing to NULL.

### Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

### PR DESCRIPTION
**Pull request by skimran2000**
# Description

Creating a double linked list with all its functions to add, delete, search and insert in C++.

Fixes #172 

## Type of change

_Please delete options that are not relevant._

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

# Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

# Screenshots:

Screenshot 2021-06-10 at 6 28 24 PM
Screenshot 2021-06-10 at 6 28 33 PM

### CODE REVIEW

**Comment by Amit366** [comment]
@skimran2000 remove the other files

**Comment by skimran2000** [comment]
I have removed the other files

**Comment by Amit366** [comment]
@skimran2000 are those two already merged??

**Comment by Amit366** [comment]
@skimran2000 don't remove those files remove the other two files

**Comment by skimran2000** [comment]
what files can you name them because i can't see the names
Please mention what files should i remove and not.

**Comment by Amit366** [comment]
. Ds store, a. Out

**Comment by Amit366** [comment]
And the other 2 files which are deleted because it is deleting from the main repo

**Comment by skimran2000** [comment]
Can you please check now, if there is still the same problem i will delete this branch and create a new PR with other branch

**Pull request merged**
