### PR TITLE
solution for problem contest start (1539A)

### LINKED ISSUE #1388: Contest Start (problem : 1539A) codeforces
# Aim

- To provide solution for the problem contest start (1539A) in c++
# Details

- This problem is based on combinatorics, maths, greedy algorithm and geometry
-  @ravikr126 @Ayush7614 @Saurabh4626 Please Assign me under LGM SOC .I will be solving in C++.

### Programming language

- [ ] C
- [ ] C++
- [ ] Java
- [ ] Python

### PR DESCRIPTION
**Pull request by kalash-kala**
# Description

provided a solution for the problem contest start (1539A) codeforces which has passed all the testcases

Fixes #1388 

## Type of change

- [ ] New feature (non-breaking change which adds functionality)

# Checklist:

- [ ] My code follows the style guidelines(Clean Code) of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings

### CODE REVIEW

**Comment by kalash-kala** [comment]
@Amit366 , @ravikr126 please review this PR

**Review by ravikr126 — APPROVED** [review]

**Comment by kalash-kala** [comment]
@Ayush7614 please review this PR

**Comment by Amit366** [comment]
@kalash-kala delete the other files which are not part of this PR.

**Comment by kalash-kala** [comment]
@ravikr126 sir ,I had a question ,when you accepted my pull request were there any unwanted files ?

**Pull request closed without merging**
