### PR TITLE
Issue #128 solved. New question added on leetcode file.

### PR DESCRIPTION
**Pull request by Ritikkumar992**
## Type of change

_Please delete options that are not relevant._

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Documentation Update

# Checklist:

- [ ] My code follows the style guidelines(Clean Code) of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have created a helpful and easy to understand `README.md`
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by Ayush7614** [comment]
@Ritikkumar992 delete previous commits this one Minor mistake resolved and this one sao

**Comment by Ritikkumar992** [comment]
@Ayush7614  I can't able to delete previous commit . Can u  help me  to know how to delete previous commit?

**Comment by Ayush7614** [comment]
@Ritikkumar992 you have to make new PR for Leetcode question i have closes this pull request

**Comment by Ritikkumar992** [comment]
ok @Ayush 7614 , I will make a new PR for the same.

**Pull request closed without merging**
