### PR TITLE
Issue1025 - Shortest Common Supersequence(DP) - C++

### PR DESCRIPTION
**Pull request by Anshika-Srivastava**
# Question

Given two strings s1 and s2 and we have to find the length of shortest supersequence consisting of both s1 and and s2.
Shortest Common Supersequence finds the shortest supersequence which consist of all the characters of both the string in the order specified. Supersequence have the same relative order but may or may not be continuous.

Fixes [#1025](https://github.com/Ayush7614/Daily-Coding-DS-ALGO-Practice/issues/1025) 

## Type of change

_Please delete options that are not relevant._

- [x] Added code

# Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by Amit366** [comment]
@Anshika-Srivastava remove the other files

**Comment by Amit366** [comment]
@Anshika-Srivastava place the code in the folder from which u have taken the question from. I think it is from Leetcode

**Comment by Anshika-Srivastava** [comment]
Actually it is dynamic programming question so I have placed it in Algorithms/Dynamic Problems/ShortestCommonSupersequence.cpp folder. Still if I should change it, please guide me ho to change the folders. @Amit366

**Comment by Amit366** [comment]
@Anshika-Srivastava I understand that it is dynamic programming concept but u have taken this question from some online platform??

**Comment by Anshika-Srivastava** [comment]
No sir! initially I didn't take it from some platform. I just did it while I was learning dynamic programming. But after searching, I saw that its there on many platforms and Leetcode is one of them. So please guide me regarding folder change.

**Comment by Amit366** [comment]
@Anshika-Srivastava are using any VSCode Or anything?

**Comment by Anshika-Srivastava** [comment]
Yes I am using VS Code. I am so srry for late replies.

**Comment by Amit366** [comment]
@Anshika-Srivastava any updates??

**Pull request closed without merging**
