### PR TITLE
tower of hanoi in java for issue number #1962

### LINKED ISSUE #1962: Tower of Hanoi under LMG SOC'21
It consists of three rods and a number of disks of different diameters, which can slide onto any rod , Only one disk may be moved at a time , Each move consists of taking the upper disk from one of the stacks and placing it on top of another stack or an empty rod , No disk may be placed on top of a disk that is smaller than it.

I would like to solve this problem using recursion where firstly I will put n-1 discs from A to B rod and then n th disc from A to C , and lastly all discs from B to C . 

### Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

### PR DESCRIPTION
**Pull request by Rounak-chauhan**
tower of hanoi in java for issue number #1962

Please include a summary of the change and which issue is fixed. List any dependencies that are required for this change.

Fixes #1962 

Replace #1962  with the issue number which is fixed in this PR

code change

_Please delete options that are not relevant._

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Documentation Update

# Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have created a helpful and easy to understand `README.md`
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by Amit366** [comment]
@Rounak-chauhan place it in proper folder

**Comment by Amit366** [comment]
Algorithm/Dynamic

**Comment by Rounak-chauhan** [comment]
done sir please check

**Comment by sameeksharl** [comment]
@Rounak-chauhan merged

**Pull request merged**
