### PR TITLE
Solution for Sort an array of 0s,1s and 2s

### LINKED ISSUE #1768: Sort an array of 0s,1s and 2s
# Aim

Want to add a solution of "Sort an array of 0s,1s and 2s"
Kindly assign me this problem. I would like to add my solution to this problem in C++ easily and efficiently using DNF sorting.
Link to the problem: https://www.geeksforgeeks.org/sort-an-array-of-0s-1s-and-2s/

# Details
Given an array A[] consisting 0s, 1s and 2s. The task is to write a function that sorts the given array. The functions should put all 0s first, then all 1s and all 2s in last.
Examples: 
 
Input: {0, 1, 2, 0, 1, 2}
Output: {0, 0, 1, 1, 2, 2}

Input: {0, 1, 1, 0, 1, 2, 1, 2, 0, 0, 0, 1}
Output: {0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2}

### Programming language

- [ ] C
- [ ] C++
- [ ] Java
- [ ] Python

### PR DESCRIPTION
**Pull request by KushagraJain58-cmd**
# Description

I have added solution for "Sort an array of 0s,1s and 2s" using c++

Fixes #1768 

## Type of change

_Please delete options that are not relevant._

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have created a helpful and easy to understand `README.md`
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by KushagraJain58-cmd** [comment]
Kindly review my PR @ravikr126

**Review by ravikr126 — APPROVED** [review]

**Review by ravikr126 — CHANGES_REQUESTED** [review]
What is histogram file??

**Comment by KushagraJain58-cmd** [comment]
I don't know how it was attached. I didn't uploaded that file. What should I do to remove this??
@ravikr126

**Comment by Amit366** [comment]
@KushagraJain58 there is also a deleted file in ur PR. So send another PR with only one file.

**Pull request closed without merging**
