### PR TITLE
Strong password

### LINKED ISSUE #2299: Strong Password- HackerRank
**Ques.**
Louise joined a social networking site to stay in touch with her friends. The signup page required her to input a name and a password. However, the password must be strong. The website considers a password to be strong if it satisfies the following criteria:

1. Its length is at least 6.
2. It contains at least one digit.
3. It contains at least one lowercase English character.
4. It contains at least one uppercase English character.
5. It contains at least one special character. The special characters are: !@#$%^&*()-+

She typed a random string of length n in the password field but wasn't sure if it was strong. Given the string she typed, can you find the minimum number of characters she must add to make her password strong?

**Details:**
image

**Programming Language:**
- [x] C++

### PR DESCRIPTION
**Pull request by inimitable034**
# Description

Added solution to the Strong Password question in java
The expected time complexity of the code is O(n). and is an efficient solution.
Fixes #2299 

 Sample test cases to better understand the problem :-
 
 1.) Password input :- Ab@2
This is not a valid password as it does not have 6 characters in total.

 2.) Password input :- Abc@123#
 This a valid password as it has all the constraints fulfilled.

- ✔This change requires a documentation update
- ✔Documentation Update

# Checklist:

 My code follows the style guidelines(Clean Code) of this project
 I have performed a self-review of my own code
 I have commented my code, particularly in hard-to-understand areas
 I have created a helpful and easy to understand `README.md`
 I have made corresponding changes to the documentation
 My changes generate no new warning
 I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by inimitable034** [comment]
Hii sir @ravikr126 
I have updated my c++ solution with tye java solution.
Added java solution for strong password in the java folder of the repo.
please accept my PR sir

**Comment by Amit366** [comment]
@inimitable034 delete other files

**Comment by inimitable034** [comment]
Done sir @Amit366
Deleted unwanted files from the commit.

**Comment by inimitable034** [comment]
This contribution is done my me under LGM-SOC 2021
@ravikr126 @Amit366

**Comment by Amit366** [comment]
@inimitable034 add test case

**Comment by inimitable034** [comment]
Thank you so much sir.
Enjoying contributing at your space.
@Amit366

**Pull request merged**
