### PR TITLE
Added Tree_Traversal.cpp under Data Structures

### PR DESCRIPTION
**Pull request by Soumyadeep-rick**
Fixes issue no. #1552 
I have added a file named **Tree_Traversal** under Data Structures.

**Summary**:
This program can be used for creating binary trees and displaying PreOrder, InOrder, and PostOrder traversals. It can also display the count of the no. of nodes present in the tree and the height of the tree.

## Type of change

_Please delete options that are not relevant._

- [x] New feature (non-breaking change which adds functionality)

# Checklist: 

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have created a helpful and easy to understand `README.md`
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works
Tree Traversal

### CODE REVIEW

**Comment by Amit366** [comment]
@Soumyadeep-rick mention issue number and add test case

**Comment by Amit366** [comment]
@Soumyadeep-rick mention issue number

**Comment by Soumyadeep-rick** [comment]
> @Soumyadeep-rick mention issue number and also delete other files

I have added issue no. which is #1552 and I have also deleted all the other files.

**Comment by Amit366** [comment]
@Soumyadeep-rick dele exe file

**Comment by Soumyadeep-rick** [comment]
I have deleted the a.exe file.

**Comment by Amit366** [comment]
@Soumyadeep-rick add test case

**Comment by Soumyadeep-rick** [comment]
This is a code of data structure, so, there is no need of any test case but then also I have added the screenshot of the entire output. Please refer to the screenshot which has already been attached.

**Comment by Amit366** [comment]
@Soumyadeep-rick there has to be some input and then the output will be displayed ,right?? That is only the test case

**Comment by Soumyadeep-rick** [comment]
**Test Case 1:**
**INPUT**
createTree 10 8 15 -1 -1 -1 -1 preOrder inOrder postOrder levelOrder height count exit
**OUTPUT**
10 8 15
8 10 15
8 15 10
10 8 15
height: 2
count: 3

**Test Case 2:**
**INPUT**
createTree 10 20 30 40 50 60 -1 -1 -1 -1 -1 -1 -1 preOrder inOrder postOrder levelOrder height count exit
**OUTPUT**
10 20 40 50 30 60
40 20 50 10 60 30
40 50 20 60 30 10
10 20 30 40 50 60
height: 3
count: 6

**Comment by Amit366** [comment]
@Soumyadeep-rick add this in the code file

**Comment by Soumyadeep-rick** [comment]
I have added the test cases in the code file, please check and confirm.

**Comment by Amit366** [comment]
@Soumyadeep-rick add this to the tree folder in data structures

**Comment by Soumyadeep-rick** [comment]
@Amit366 I have added this code under the Tree folder in Data Structure.

**Pull request merged**
