### PR TITLE
operation on linked list in java with issue number#184

### PR DESCRIPTION
**Pull request by Rounak-chauhan**
#  @Amit366 since you have assigned me to work on different operation in linked list in java

Please include a summary of the change and which issue is fixed. List any dependencies that are required for this change.
operation in linkedlist in java the following code is in java language and had following operation:
1)insert at start
2)insert at end
3)insert at any position
4)delete
5)searching for a number in linked list
6)sorting
7)get middle element

Fixes #(184)

Replace `#184` with the issue number which is fixed in this PR

#184 
_Please delete options that are not relevant._

- [ ] New feature (non-breaking change which adds functionality)

- [ ] This change requires a documentation update
- [ ] Documentation Update

# Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by Rounak-chauhan — COMMENTED** [review]
first code is for operation in linked list

**Comment by Amit366** [comment]
@Rounak-chauhan remove the other files

**Comment by Amit366** [comment]
@Rounak-chauhan no

**Comment by Rounak-chauhan** [comment]
@Amit366  sir please tell which file i need to delete and how should i delete that

**Comment by Rounak-chauhan** [comment]
@Amit366 sir please help me i deleted 01knapsack and intersection but not able to delete other merge files

**Comment by Rounak-chauhan** [comment]
@Amit366 @Ayush7614 sir i had deleted the other files please check and if they are not deleted the please let me know which files are not deleted .

**Comment by Amit366** [comment]
@Rounak-chauhan these files were already present in the main repo

**Comment by Rounak-chauhan** [comment]
sir me new pull request generate kar raha hu

**Pull request closed without merging**
