### PR TITLE
Finding Factorial

### PR DESCRIPTION
**Pull request by Ashu-1309**
# Description

Finding the factorial of a number 

Fixes #1454

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have created a helpful and easy to understand `README.md`
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by Amit366** [comment]
@Ashu-1309 add test case

**Comment by Ashu-1309** [comment]
What I have to add put in test case .

**Comment by Amit366** [comment]
@Ashu-1309 just refer the merged PR 1316

**Comment by Ashu-1309** [comment]
You I have to add comment in my code . As all the things are similar  except comment which he gave it in his code  .

**Comment by Amit366** [comment]
@Ashu-1309 check the test cases

**Comment by Ashu-1309** [comment]
Done

**Comment by Ashu-1309** [comment]
I have done all the changes that required

**Comment by Ashu-1309** [comment]
What I have to do now ??

**Pull request merged**
