### PR TITLE
Added find distance between two nodes of a Binary Tree under GFG

### LINKED ISSUE #877: Find the Distance between two nodes in Binary Search Tree
# Aim

- To Find the Distance between two nodes in Binary Search Tree. Find the distance between two keys in a binary tree, no parent pointers are given.

# Details

- This code will find the distance between two nodes in Binary Search Tree. 
- The distance between two nodes is the minimum number of edges to be traversed to reach one node from another.
- nodedistancebst

### Programming language

- [ ] C
- [ ] C++
- [x] Java
- [ ] Python

Link for the problem - https://practice.geeksforgeeks.org/problems/min-distance-between-two-givennodes-of-a-binary-tree/1 ]

### PR DESCRIPTION
**Pull request by SNEHAL311998**
# Description

The aim is to find the distance between two nodes in Binary Search Tree. The distance between two nodes is the minimum number of edges to be traversed to reach one node from another.

nodedistancebst

Problem Link: https://practice.geeksforgeeks.org/problems/min-distance-between-two-given-nodes-of-a-binary-tree/1

Fixes #877

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by SNEHAL311998** [comment]
Please review my pull request. I have detailed about the problem that I have solved

**Comment by Amit366** [comment]
@SNEHAL311998 mention the issue number

**Comment by SNEHAL311998** [comment]
i have already mentioned it #877

**Comment by Amit366** [comment]
@SNEHAL311998 add a test case at the bottom of the code

**Comment by SNEHAL311998** [comment]
Added a test case in bottom of code.
nodedistancebst_output

**Comment by Amit366** [comment]
@SNEHAL311998 u have added 2 files

**Comment by SNEHAL311998** [comment]
I have removed the extra file please review my pull request

**Comment by aviral14112001** [comment]
@Amit366  Please assign me this task under " LGM SoC 21 " I will like to provide a detailed solution to this problem in C++

**Comment by Amit366** [comment]
@aviral14112001 comment it in the issue section

**Pull request merged**
