### PR TITLE
Issue #374

### LINKED ISSUE #374: Implement ChainHashing
It will work for non negative integers
Language : C++

### PR DESCRIPTION
**Pull request by pritmanvar**
# Description

Fixes #374

Replace `374` with the issue number which is fixed in this PR

## Type of change
Added a file

- [ ] My code follows the style guidelines(Clean Code) of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Comment by pritmanvar** [comment]
i had created a PR please check it

**Comment by Amit366** [comment]
@pritmanvar resolve conflict

**Comment by Amit366** [comment]
@pritmanvar resolve the conflict

**Comment by pritmanvar** [comment]
It was showing error like "These conflicts are too complex to resolve in
this web browser" and I don't know how to solve this issue.
Can you guide me?

**Comment by Amit366** [comment]
Do one thing close this PR and update ur forked repo. Then send the PR @pritmanvar

**Pull request closed without merging**
