### PR TITLE
Zig-Zag Traversal of a Binary Tree 

### LINKED ISSUE #709: Zig-Zag Traversal of a Binary Tree
I want to provide a C++ code for implementation of binary tree using Zig-Zag traversal.
I am LGM-SOC participant and want to provide this code with proper comments and explanation.

Please assign me this issue.

### PR DESCRIPTION
**Pull request by kumarshobhit**
# Description

Please include a summary of the change and which issue is fixed. List any dependencies that are required for this change.

Fixes #709 

Replace `issue_no` with the issue number which is fixed in this PR

## Type of change

_Please delete options that are not relevant._

- [x] New feature (non-breaking change which adds functionality)
- image

# Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have created a helpful and easy to understand `README.md`
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by Amit366** [comment]
@kumarshobhit please check the path

**Comment by kumarshobhit** [comment]
can you please elaborate?

**Comment by kumarshobhit** [comment]
should I insert the file simply under the leet code directory without creating a new Tree directory?

**Comment by Amit366** [comment]
Yes

**Comment by kumarshobhit** [comment]
Tree directory was already created before my commit. I had further created a directory Binary Tree which now I have removed. Please check.

**Comment by Amit366** [comment]
@kumarshobhit there is no Tree folder in Leetcode

**Comment by kumarshobhit** [comment]
Oh yes. I updated the main branch of my forked reop but  I forgot to update the branch in which I was working.

**Comment by kumarshobhit** [comment]
File path modified.

**Pull request merged**
