### PR TITLE
added code for duplicate number

### LINKED ISSUE #2159: Find the Duplicate Number leetcode medium under lgmsoc
# Aim
i would like to work on this issue using bit manipulation

# Details
287. Find the Duplicate Number
Medium

Given an array of integers nums containing n + 1 integers where each integer is in the range [1, n] inclusive.

There is only one repeated number in nums, return this repeated number.

You must solve the problem without modifying the array nums and uses only constant extra space.

 

Example 1:

Input: nums = [1,3,4,2,2]
Output: 2

### Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

### PR DESCRIPTION
**Pull request by SnehaAgarwal361**
# Description

Fixes #2159

# Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have created a helpful and easy to understand `README.md`
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by Amit366** [comment]
@SnehaAgarwal361 add main function

**Comment by SnehaAgarwal361** [comment]
Sir but in leetcode we are not supposed to write the main function it gives error if we change func prototype or even add any.

**Comment by Amit366** [comment]
@SnehaAgarwal361 but this is not Leetcode, this is open source. Here u have to write the entire code.

**Comment by SnehaAgarwal361** [comment]
Okay sir actually all the previous files added in the repo are in the same pattern so i did that in that way..please consider this time i will make sure to write complete code from the next issue.

**Comment by Amit366** [comment]
@SnehaAgarwal361 all the files in the repo are with the main function. And without main function it won't be accepted.

**Comment by SnehaAgarwal361** [comment]
Sorry but i had reference from a problem Reorganize strings from c++ folder of leetcode.

**Pull request merged**
