### PR TITLE
Intersection of two sorted arrays

### LINKED ISSUE #269: Intersection of two sorted arrays
@Ayush7614 @Amit366 Please assign me this issue I would like to solve this question as a part of the LGM-SOC'21 contest.

Given two sorted arrays, find their intersection .
Example:

Input : arr1[] = {1, 2, 4, 5}
arr2[] = {2, 3, 5}
Output : Intersection : {2, 5}

I will be using CPP.

### PR DESCRIPTION
**Pull request by Amit-45**
Problem : Given two sorted arrays find their intersection .
Language used : C++

Fixes #269

Checklist:
-My code follows the style guidelines(Clean Code) of this project
-I have performed a self-review of my own code
-I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Comment by Amit366** [comment]
@Amit-45 remove the other file

**Comment by Amit-45** [comment]
@Amit366  Now is it ok ?

**Comment by Amit366** [comment]
@Amit-45 which file did u add??

**Comment by Amit-45** [comment]
I have deleted the extra file -union of two sorted arrays.cpp.
My pull request was to add the file -intersection of two sorted arrays.cpp.

Please review my pull request .Even after this if the problem continues then I will create a new pull request for the same issue .

**Pull request closed without merging**
