### PR TITLE
Added code for Issue796

### PR DESCRIPTION
**Pull request by Anshika-Srivastava**
# Question

Rod Cutting Problem

Fixes [#796](https://github.com/Ayush7614/Daily-Coding-DS-ALGO-Practice/issues/796)

# Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by Amit366** [comment]
@Anshika-Srivastava remove the other file

**Comment by Anshika-Srivastava** [comment]
Can you help me regarding how to remove?

**Comment by Amit366** [comment]
@Anshika-Srivastava did u see the message in the slack about the PR??

**Comment by Anshika-Srivastava** [comment]
Yes you can have a look!

**Comment by Amit366** [comment]
@Anshika-Srivastava test case??

**Comment by Anshika-Srivastava** [comment]
Hey @Amit366 ! I have updated the test case. Sorry for being a bit late as I was occupied with some college work.
Thank You:)

**Pull request merged**
