### PR TITLE
Array Implementation of Stack

### LINKED ISSUE #195: Implementing stack using array
In array implementation, the stack will be formed by using an array and the operations regarding the stack like push and pop will be performed using arrays.

I want to work on this issue in C++ language.

I request @Ayush7614 to assign me this issue for LGM SOC'21.

### PR DESCRIPTION
**Pull request by div0510**
INCLUDES push and pop function

Fixes #195 

## Type of change

_Please delete options that are not relevant._

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

# Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas

- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by Amit366** [comment]
@div0510 place the file in the Data Structure folder

**Comment by div0510** [comment]
> 
> 
> @div0510 place the file in the Data Structure folder

@Amit366  Can you please guide me how can I place this in DATA STRUCTURES folder

**Comment by Amit366** [comment]
@div0510 see in ur text editor just cut this file and paste it in the data structure folder

**Comment by div0510** [comment]
Sir I am unable to process this please provide me sets to do this change

**Comment by Amit366** [comment]
@div0510 may I know which editor are u using??

**Comment by div0510** [comment]
I copy my code from Vs code  and then paste it here  and make the commit

**Comment by Amit366** [comment]
@div0510 then do one thing paste it in the Data structure folder

**Comment by Amit366** [comment]
And delete from Hackerrank folder

**Comment by div0510** [comment]
Sir, I have deleted it from hackerrank folder and placed the new file in the data structures folder  @Amit366

**Comment by div0510** [comment]
@Amit366  Sir please can you let me know how can I make a new folder since I need to add code for the patterns

**Comment by Amit366** [comment]
> Sir, I have deleted it from hackerrank folder and placed the new file in the data structures folder @Amit366

@div0510 Then commit it

**Comment by div0510** [comment]
> 
> 
> > Sir, I have deleted it from hackerrank folder and placed the new file in the data structures folder @Amit366
> 
> @div0510 Then commit it

I have made a commit

**Comment by Amit366** [comment]
@div0510 it's not reflecting over here. Do one thing close this issue and then add it to data structure folder

**Comment by div0510** [comment]
#443 sir please check this pull request

**Pull request closed without merging**
