### PR TITLE
Fenced Matrix using Python

### LINKED ISSUE #597: Fenced Matrix (Python)
### **Description :** 
You will be given two positive integers m and n. You have to make a list of lists (which can be visualised as a matrix) of size m*n, that is m sublists (rows), with each sublists having n integers (columns). The matrix should be such that it should have 1 on the border and 0 everywhere else. 

**_Solution :_** 
Using Concept of List Comprehension and Shallow copying in Python

l1
l2

 **_Programming language_**
-  C
-  C++
-  Java
- ✔ Python

### PR DESCRIPTION
**Pull request by singhmansi25**
- Fenced Matrix
- LGM-SOC'21 Participant
- Author : Mansi Singh

# Description
The issue was generated by  the author and two solutions have been provided to make understand others the concept of list, list comprehension, deep and shallow copy methods in Python. The project can be performed on Jupyter Notebook or Google Colab. 

Two solutions have been provided for better understanding where one uses library while other doesn't.

Fixes #597 

## Type of change

- [✔] New feature (non-breaking change which adds functionality)

# Checklist:

- [ ✔] My code follows the style guidelines(Clean Code) of this project
- [✔ ] I have performed a self-review of my own code
- [✔ ] I have commented my code, particularly in hard-to-understand areas
- [✔ ] I have created a helpful and easy to understand `README.md`
- [ ] I have made corresponding changes to the documentation   -------------------------------- Not Required
- [ ✔] My changes generate no new warnings
- [✔ ] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by Amit366** [comment]
@singhmansi25 delete other files

**Comment by singhmansi25** [comment]
Hey, after deleting other files, do I need to do PR again ???

**Comment by Amit366** [comment]
@singhmansi25 is it a question from any online coding platform?? If yes then face it in the respective folder

**Comment by singhmansi25** [comment]
Actually, its not from any platform. That's why I posted it in Data
Structures.
Please tell further details.

**Comment by Amit366** [comment]
@singhmansi25 ok but atleast add test case

**Comment by singhmansi25** [comment]
Test Case in the form of images ?? Then do I need to do PR again ??
Please let me know.

**Comment by Amit366** [comment]
Just add it below the code. Look at other PRs.

**Comment by Amit366** [comment]
@singhmansi25 any updates??

**Comment by singhmansi25** [comment]
Yeah, I have made the changes. Do I need to do PR again ??

**Pull request merged**
