### PR TITLE
Added Rabin Karp algorithm in C

### LINKED ISSUE #397: Rabin Karp Algorithm
Rabin Karp algorithm matches the hash value of the pattern with the hash value of current substring of text, and if the hash values match then only it starts matching individual characters. So Rabin Karp algorithm needs to calculate hash values for following strings.
1) Pattern itself. 
2) All the substrings of the text of length m. 

### Programming language

- [ ] C
- [ ] C++
- [ ] Java
- [x] Python

### PR DESCRIPTION
**Pull request by mitali-1703**
# Description

Added Rabin Karp algorithm in C with proper implementation.

Fixes #397 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by Ayush7614** [comment]
Remove Prevoius File @mitali-1703

**Comment by mitali-1703** [comment]
> Remove Prevoius File @mitali-1703

Sorry I didn't get you. Which previous file are you talking about @Ayush7614

**Comment by mitali-1703** [comment]
> Remove Prevoius File @mitali-1703

I have removed other files. Now you may merge this @Ayush7614

**Comment by Amit366** [comment]
@mitali-1703 this is same as https://gist.github.com/ashnigga98/4cd98db376c28323b3be94655829bed6

**Pull request closed without merging**
