### PR TITLE
1628 merge k sorted linked list python code

### LINKED ISSUE #1628: Merge K sorted Linked List (Leetcode: Hard)
# Aim

To create a function that solves the problem
# Details

Given a pointer of Linked List Merge all of them in ascending order
### Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

## Leetcode Hard Difficulty Problem [Link](https://leetcode.com/problems/merge-k-sorted-lists/)
Approach used: using Priority Queue

### PR DESCRIPTION
**Pull request by sonamgupta136**
# Description

Merge K sorted Linked List Python Solution.

Fixes #1628

# Checklist:

- [ ] My code follows the style guidelines(Clean Code) of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings

### CODE REVIEW

**Comment by sonamgupta136** [comment]
@Amit366 please review

**Comment by Amit366** [comment]
@sonamgupta136 delete the other file which is not a part of this issue

**Comment by Amit366** [comment]
@sonamgupta136 add the main function

**Comment by sonamgupta136** [comment]
#1628 @Amit366 please review now

**Pull request merged**
