### PR TITLE
BFS Graph Traversal

### PR DESCRIPTION
**Pull request by kumarshobhit**
# Description

BFS Graph Traversal

Fixes #176 

## Type of change

- [x] New feature (non-breaking change which adds functionality)
image

# Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have created a helpful and easy to understand `README.md`
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by Ayush7614** [comment]
image

**Comment by Ayush7614** [comment]
image

**Comment by Ayush7614** [comment]
@kumarshobhit your file is empty what is this mke new PR i will close this

**Comment by kumarshobhit** [comment]
yes apologies for the error. I will make a new one

**Pull request closed without merging**
