### PR TITLE
Josephus problem added using C++

### LINKED ISSUE #674: Josephus Problem
@Ayush7614 

AIM :

Josephus Problem using recursion in c++.

please assign me this...

### Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

### PR DESCRIPTION
**Pull request by ArshWalker**
# Description

This a Josephus Problem.
The problem is named after Flavius Josephus, a Jewish historian living in the 1st century. According to Josephus' account of the siege of Yodfat, he and his 40 soldiers were trapped in a cave by Roman soldiers. They chose suicide over capture and settled on a serial method of committing suicide by drawing lots.

Fixes #674 

image

## Type of change

_Please delete options that are not relevant._

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by ArshWalker** [comment]
@Ayush7614 please review this.

**Review by ravikr126 — COMMENTED** [review]
Can you add question as well as testcases in this pr.

**Comment by ArshWalker** [comment]
Can I ask you what kind of questions you're expecting?
Or do I need to make separate file?
@ravikr126

**Comment by ravikr126** [comment]
Add question and test cases in comment in the code @ArshWalker

**Comment by ArshWalker** [comment]
Ok sure, would you please review my pr for issue #991 bucket sort using python.

**Comment by Amit366** [comment]
@ArshWalker any update??

**Comment by ArshWalker** [comment]
Will do it by today @Amit366 , actually I was sick before.

**Comment by Amit366** [comment]
Any update?

**Review by ravikr126 — APPROVED** [review]

**Pull request merged**
