### PR TITLE
operation in linked list #184

### PR DESCRIPTION
**Pull request by Rounak-chauhan**
#1780 
 different kinds of operation in linked list in java language which include following function:
insert
delete
searching
sorting
middle element

Fixes (#184 )

Replace `issue_no` with the issue number which is fixed in this PR

## deleted unwanted avoid files in my PR

_Please delete options that are not relevant._

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Documentation Update

# Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have created a helpful and easy to understand `README.md`
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by Rounak-chauhan** [comment]
@Amit366  sir i had generated new pull request by making certain changes in old one please review it

**Comment by Amit366** [comment]
@Rounak-chauhan don't delete the file from the github itself since the files already present in the repo ,and u deleted them.

**Comment by Rounak-chauhan** [comment]
@Amit366 sir what should i do now sir i new to github so please guide me what to do i m got confused in these delete things

**Comment by Amit366** [comment]
@Rounak-chauhan copy ur code in the notepad and delete it from ur text editor. Then pull the upstream and then add ur code to the text editor and then create Pull request. Remember to change the branch

**Comment by Amit366** [comment]
you can dm me for further doubts

**Pull request closed without merging**
