### PR TITLE
solving problem of tower of hanoi using recursion in c++

### LINKED ISSUE #1962: Tower of Hanoi under LMG SOC'21
It consists of three rods and a number of disks of different diameters, which can slide onto any rod , Only one disk may be moved at a time , Each move consists of taking the upper disk from one of the stacks and placing it on top of another stack or an empty rod , No disk may be placed on top of a disk that is smaller than it.

I would like to solve this problem using recursion where firstly I will put n-1 discs from A to B rod and then n th disc from A to C , and lastly all discs from B to C . 

### Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

### PR DESCRIPTION
**Pull request by simarjeet30**
# Description

Tower of Hanoi is a mathematical puzzle where we have three rods and n disks. The objective of the puzzle is to move the entire stack to another rod, obeying the following simple rules: 

1. Only one disk can be moved at a time.
2. Each move consists of taking the upper disk from one of the stacks and placing it on top of another stack i.e. a disk can only be moved if it is the uppermost disk on a stack.
3. No disk may be placed on top of a smaller disk.

Fixes #1962

Replace `issue_no` with the issue number which is fixed in this PR

## Type of change

_Please delete options that are not relevant._

- [ ] New feature (non-breaking change which adds functionality)

# Checklist:

- [ ] My code follows the style guidelines(Clean Code) of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have created a helpful and easy to understand `README.md`
Capture 4

- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by Amit366** [comment]
@simarjeet30 place it proper folder

**Comment by simarjeet30** [comment]
@Amit366 ,I am placing it in  Algorithms>Miscellaneous>C++.

**Comment by sameeksharl** [comment]
@simarjeet30 place it in dynamic problems/c++

**Comment by simarjeet30** [comment]
@sameeksharl ,I did it please check now .

**Comment by sameeksharl** [comment]
@simarjeet30 merged into main

**Pull request merged**
