### PR TITLE
Issue #376

### LINKED ISSUE #376: Search in Rotated Sorted Array
* Problem : There is an integer array nums sorted in ascending order (with distinct values).

 Prior to being passed to your function, nums is rotated at an unknown pivot index k (0 <= k < nums.length) such that the 
 resulting array is [nums[k], nums[k+1], ..., nums[n-1], nums[0], nums[1], ..., nums[k-1]] (0-indexed). For example, 
 [0,1,2,4,5,6,7] might be rotated at pivot index 3 and become [4,5,6,7,0,1,2].

 Given the array nums after the rotation and an integer target, return the index of target if it is in nums, or -1 if it is not in 
 nums.
 
You must write an algorithm with O(log n) runtime complexity.
* Problem Link : https://leetcode.com/problems/search-in-rotated-sorted-array/
* Platform : LeetCode
* Language : C++

### PR DESCRIPTION
**Pull request by pritmanvar**
# Description

Fixes #376

Replace `376` with the issue number which is fixed in this PR

## Type of change

added a file

- [ ] My code follows the style guidelines(Clean Code) of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Comment by pritmanvar** [comment]
I had made an PR.
Please review it

**Comment by pritmanvar** [comment]
forgot to add main function

**Comment by pritmanvar** [comment]
added main function in both

**Comment by Amit366** [comment]
@pritmanvar remove the other file

**Comment by Ayush7614** [comment]
@pritmanvar resolve conflict and remove previous files

**Comment by pritmanvar** [comment]
conflicts resolved

**Pull request merged**
