### PR TITLE
Added Indian Coin Change Problem

### LINKED ISSUE #730: Indian Coin Change Problem
Hey @Ayush7614 
I would like to add Indian Coin Change Problem in C++.
Please assign me.

# Details
It is based on Greedy Approach, where user enter certain numbers and the limit and gets the output of the coins.

### Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

### PR DESCRIPTION
**Pull request by Shaishav0507**
# Description

Indian coin change problem gives the number of changes to be needed to make that number.
Done in C++
Given proper explanation.
Thanks

Fixes #730 

Replace `issue_no` with the issue number which is fixed in this PR

## Type of change

_Please delete options that are not relevant._

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Documentation Update

# Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by Amit366** [comment]
@Shaishav0507 this is similar to https://tutorialspoint.dev/algorithm/greedy-algorithms/greedy-algorithm-to-find-minimum-number-of-coins

**Comment by Shaishav0507** [comment]
@Amit366 
Brother if you know code remains same in every site.
Plus this is the code I worte.
No issues if you closed.

**Comment by Amit366** [comment]
It is 60% same and yes I agree that the headers remain same, but even the variables and the function name cannot remain exactly same. @Shaishav0507  and yes we said we won't tolerate plagiarism.

**Comment by Shaishav0507** [comment]
Should I make another PR @Amit366

**Comment by Shaishav0507** [comment]
> Should I make another PR @Amit366

With necessary changes of my own

**Comment by Shaishav0507** [comment]
And it's not exactly same .

**Comment by Amit366** [comment]
Yes u can

**Comment by Shaishav0507** [comment]
Ok I'll do that.
Don't close the issue

**Pull request closed without merging**
