### PR TITLE
Added Solution of  Pow(x,n) (LeetCode) in Python under LGMSOC'21

### LINKED ISSUE #1538: Solution of Pow(x,n) (Leetcode) in Python under LGMSOC'21.
# Aim

- Want to add solution of Pow(x,n) in Python under LGMSOC'21.

# Details

- Problem Link - https://leetcode.com/problems/powx-n/

### Language used - Python

@Ayush7614 @ravikr126 please assign me this issue.

### Programming language

- [ ] C
- [ ] C++
- [ ] Java
- [x] Python

### PR DESCRIPTION
**Pull request by rajeshkumar2024**
# Description

Added Solution of  Pow(x,n) (LeetCode) in Python with some example test cases under LGMSOC'21

Fixes #1538 

Replace `issue_no` with the issue number which is fixed in this PR

## Type of change

_Please delete options that are not relevant._

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by Amit366** [comment]
@rajeshkumar2024 main function??

**Comment by rajeshkumar2024** [comment]
@Amit366   In leetcode we get only solution class to solve. That's why i have attached only Solution class.

**Comment by Amit366** [comment]
@rajeshkumar2024 this is not leetcode, this is open source where you need to write the entire code.

**Comment by rajeshkumar2024** [comment]
@Amit366 ok I will add the entire code then I will raise PR.

**Pull request closed without merging**
