### PR TITLE
Create middle_of_three

### LINKED ISSUE #2034: Middle of three using minimum comparison
# Aim

- Middle of three using minimum comparison

# Details

- Given three distinct numbers A, B and C. Find the number with value in middle (Try to do it with minimum comparisons)

### Programming language
- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

### PR DESCRIPTION
**Pull request by baljeet-singh97**
# Description

middle element with minimum comparisons

Fixes #2034 

## Type of change

_Please delete options that are not relevant._

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Documentation Update

# Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by baljeet-singh97** [comment]
review my pr @ravikr126

**Comment by ravikr126** [comment]
Add question and test cases @baljeet-singh97

**Review by ravikr126 — CHANGES_REQUESTED** [review]
Add test cases and question

**Comment by baljeet-singh97** [comment]
added question and test cases @ravikr126 @Ayush7614

**Comment by baljeet-singh97** [comment]
added question and test cases @ravikr126 @Ayush7614

**Review by ravikr126 — APPROVED** [review]

**Pull request merged**
