### PR TITLE
Siddhi 244 infix

### LINKED ISSUE #171: Infix to Postfix
# Aim

- Convert the infix expression to postfix expression using stack data structure

# Details

- By scanning the infix expression from left to right, when I will get any operand, simply add them to the postfix form, and when I get operator and parenthesis, add them in the stack maintaining the precedence of them. At the end pop the stack out completely to get postfix expression

### Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

### PR DESCRIPTION
**Pull request by siddhi-244**
# Description

Added infix to postfix conversion in stack(python)

Fixes #171 

# Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x]  My code generates no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works
Screenshot_20210611-141726_Chrome

### CODE REVIEW

**Review by toth2000 — CHANGES_REQUESTED** [review]
The code needs the following changes:
- You are here just printing the array in reverse. You need to actually reverse the array which means if the array is 1 2 3 4 5 then it should be 5 4 3 2 1, i.e arr[0] after reversing should give 5.
- You are allocating the array like arr[n] which may produce an error. Try to use dynamic allocation to allocate memory to the array.

**Comment by siddhi-244** [comment]
> The code needs the following changes:
> 
> * You are here just printing the array in reverse. You need to actually reverse the array which means if the array is 1 2 3 4 5 then it should be 5 4 3 2 1, i.e arr[0] after reversing should give 5.
> * You are allocating the array like arr[n] which may produce an error. Try to use dynamic allocation to allocate memory to the array.

This is another pr this is about infix to postfix coversion

**Comment by toth2000** [comment]
> > The code needs the following changes:
> > 
> > * You are here just printing the array in reverse. You need to actually reverse the array which means if the array is 1 2 3 4 5 then it should be 5 4 3 2 1, i.e arr[0] after reversing should give 5.
> > * You are allocating the array like arr[n] which may produce an error. Try to use dynamic allocation to allocate memory to the array.
> 
> This is another pr this is about infix to postfix coversion

Oh sorry! my bad I clicked on the wrong file. 😅

**Comment by Amit366** [comment]
@siddhi-244 I am merging this but take input from user don't just use any expression of ur own.

**Comment by siddhi-244** [comment]
Ok sir sure

**Comment by siddhi-244** [comment]
Sir do I open a new issue and take a input or let it be @Amit366 ?

**Comment by Amit366** [comment]
This issue is solved now work on other issues @siddhi-244

**Comment by siddhi-244** [comment]
Ok sir!

**Pull request merged**
