### PR TITLE
Parentheses Checker

### PR DESCRIPTION
**Pull request by Arkashish**
# Parentheses Checker program using c++

please merge my pull request

### CODE REVIEW

**Comment by Amit366** [comment]
@Arkashish add test case

**Comment by Arkashish** [comment]
In the question right? @Amit366

**Comment by Amit366** [comment]
@Arkashish add test cases below the code

**Review by Arkashish — COMMENTED** [review]
Test Cases added

**Comment by Amit366** [comment]
@Arkashish just mention the issue and also place the code in the folder from which u have taken the question from

**Pull request closed without merging**
