### PR TITLE
Transitive_Closure_of_Graph.cpp

### LINKED ISSUE #918: Transitive closure of a graph
Given a directed graph, find out if a vertex j is reachable from another vertex i for all vertex pairs (i, j) in the given graph. Here reachable mean that there is a path from vertex i to j. The reach-ability matrix is called the transitive closure of a graph.

Graph is given in the form of adjacency matrix say ‘graph[V][V]’ where graph[i][j] is 1 if there is an edge from vertex i to vertex j or i is equal to j, otherwise graph[i][j] is 0

Please assign me this question as a part of LGMSOC 21.
Question Link : https://www.geeksforgeeks.org/transitive-closure-of-a-graph/

### Programming language

- [ ] C
- [ ] C++
- [ ] Java
- [ ] Python

### PR DESCRIPTION
**Pull request by ayshi028**
# Description

Please include a summary of the change and which issue is fixed. List any dependencies that are required for this change.

Fixes #918 

Replace `#918` with the issue number which is fixed in this PR

## Type of change

_Please delete options that are not relevant._

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Documentation Update

# Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have created a helpful and easy to understand `README.md`
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by Amit366** [comment]
@ayshi028 add the extension in file name

**Comment by ayshi028** [comment]
@Amit366 what extension do I need to add?

**Comment by Amit366** [comment]
@ayshi028 u need to add  . c at the end of the file name

**Comment by ayshi028** [comment]
@Amit366  could you kindly check if its okay or not

**Comment by Amit366** [comment]
@ayshi028 in which language have u done it ?

**Comment by ayshi028** [comment]
I have done in cpp

**Comment by ayshi028** [comment]
@Amit366 look into it

**Comment by Amit366** [comment]
@ayshi028 then stdio.h is used in c , in cpp it is iostream .

**Comment by Amit366** [comment]
And also add test case

**Comment by ayshi028** [comment]
But the code is running fine in cpp compiler
Please check @Amit366

**Comment by ayshi028** [comment]
@Amit366  sorry for error,i have updated the code

**Comment by Amit366** [comment]
@ayshi028 add test case

**Comment by ayshi028** [comment]
Input: N = 4
graph = {{1, 1, 0, 1}, 
         {0, 1, 1, 0}, 
         {0, 0, 1, 1}, 
         {0, 0, 0, 1}}
Output: {{1, 1, 1, 1}, 
         {0, 1, 1, 1}, 
         {0, 0, 1, 1}, 
         {0, 0, 0, 1}}
Explaination: The output list shows the 
reachable indexes.

**Comment by ayshi028** [comment]
@Amit366 please check

**Comment by Amit366** [comment]
@ayshi028 add the test case in the code file

**Comment by ayshi028** [comment]
@Amit366  done

**Pull request merged**
