### PR TITLE
Added Print Ancestors of a given node in Binary Tree

### PR DESCRIPTION
**Pull request by Rajspeaks**
Added Print Ancestors of a given node in Binary Tree-GfG

### CODE REVIEW

**Comment by Amit366** [comment]
@Rajspeaks delete the other file

**Comment by Rajspeaks** [comment]
Done

**Comment by Amit366** [comment]
@Rajspeaks mention the issue number

**Comment by Rajspeaks** [comment]
Issue No.: #1321
PR No. #1043 
Added test case to the program
(OUTPUT: 4 2 1 )

**Comment by Amit366** [comment]
@Rajspeaks comment the output in code file

**Comment by Rajspeaks** [comment]
Yes already included in code

**Comment by Amit366** [comment]
@Rajspeaks add single line comment to the output

**Comment by Rajspeaks** [comment]
Yes done.

**Comment by Amit366** [comment]
@Rajspeaks this is similar to https://tutorialspoint.dev/data-structure/binary-tree-data-structure/print-ancestors-of-a-given-node-in-binary-tree

**Pull request closed without merging**
