### PR TITLE
added code to find third largest element in the given array

### LINKED ISSUE #779: Third Largest Element in C++
**Is your feature request related to a problem? Please describe.**
I want to add this question in GFG section. This question is about to finding third largest element in the given array. Please assign me . 
Thank you :)

### Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

### PR DESCRIPTION
**Pull request by RoliGautam**
# Description

I added code to find the third largest element in the given array in C++ under the  GFG folder.

Fixes #779

Replace `issue_no` with the issue number which is fixed in this PR

## Type of change

_Please delete options that are not relevant._

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by RoliGautam** [comment]
Please have a look on my code and merge it @Ayush7614 
Thank you:)

**Comment by Amit366** [comment]
@RoliGautam remove the exe file

**Comment by RoliGautam** [comment]
ok

**Comment by RoliGautam** [comment]
I deleted exe file and again create a pull request .. 
Please have a look @Amit366

**Comment by Amit366** [comment]
So I am closing this PR.

**Pull request closed without merging**
