### PR TITLE
Added all possible solutions to rat in maze problem and a screenshot depicting the examples

### LINKED ISSUE #423: Rat In Maze Java
For a 3x3 matrix, if the rat is initially at (0,0) position and it wants to reach at position (2,2) then print all the ways in which the rat can reach the endpoint of the maze. The rat can move only in horizontal or vertical directions.

For example:
Input: 
Starting row: 0
Starting col: 0
Ending row: 2
Ending col: 2

Output:
HHVV
HVHV
HVVH
VHHV
VHVH
VVHH

Please assign this issue to me under LGM SOC21

### PR DESCRIPTION
**Pull request by surajm-333**
# Description

Added the solution to the rat in maze problem in the Java language. I tried to print all possible solutions to this problem using recursion. I have explained the code using comments wherever required. I have also added a screenshot that shows different possible answers printed for different inputs.

Fixes #423 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by surajm-333** [comment]
I have also added a screenshot for clear understanding. This is the screenshot that I have added. @Ayush7614 @Amit366 
RatInMazeRecursionExample

**Comment by Amit366** [comment]
@surajm-333 delete the other file

**Comment by surajm-333** [comment]
It is the example screenshot of the code that by taking custom inputs. Should I delete it?

**Comment by Amit366** [comment]
@surajm-333 yes delete it

**Comment by surajm-333** [comment]
@Amit366 I have deleted the file.

**Pull request merged**
