### PR TITLE
Added Shell sort algo in C

### LINKED ISSUE #675: Shell Sort in C++
### Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

### PR DESCRIPTION
**Pull request by mitali-1703**
# Description

Added Shell sort algo in C.

Fixes #675

## Type of change

- [ ] New feature (non-breaking change which adds functionality)

# Checklist:

- [ ] My code follows the style guidelines(Clean Code) of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings

### CODE REVIEW

**Comment by mitali-1703** [comment]
@Ayush7614 @Amit366 plz review this PR and merge it adding labels to it...thnx

**Comment by Amit366** [comment]
@mitali-1703 add test case

**Comment by mitali-1703** [comment]
@Amit366 done!!

**Comment by Amit366** [comment]
@mitali-1703 where have u added the test cases?? Please review other PRs

**Comment by mitali-1703** [comment]
> @mitali-1703 where have u added the test cases?? Please review other PRs

Ok

**Comment by kamleshjoshi8102** [comment]
> @mitali-1703 where have u added the test cases?? Please review other PRs

https://titanwolf.org/Network/Articles/Article?AID=882c7060-2ece-4411-ae25-d9309548b08f#gsc.tab=0

: )

**Comment by Amit366** [comment]
@kamleshjoshi8102 what is this?

**Comment by kamleshjoshi8102** [comment]
> @kamleshjoshi8102 what is this?

C Program to sort an array using Shell Sort technique!

which is plagiarized I guess

**Comment by Amit366** [comment]
@mitali-1703 this is similar to above link

**Comment by Amit366** [comment]
@kamleshjoshi8102 u said Prs which are merged are plagiarized but this PR wasn't merged. So before u say anything first be clear. And I am warning you next time if u say that merged Prs are plagiarized but that PR is unmerged then u will be banned from LGMSOC

**Pull request closed without merging**
