### PR TITLE
Added Silver and Gold problem from gfg Job-A-Thon

### LINKED ISSUE #2314: Silver and Gold (GFG)(JOB-A-Thon)
# Details

I would like to write code on Silver and Gold Problem which was asked in GeeksforGeeks Job-A-Thon: For Internship Contest

**Problem statement:**

There are N coins kept in a line. Each coin has two sides - one is colored gold and the other silver. You can flip two adjacent coins any number of times. You need to make the gold-colored side of every coin facing up. You are given the initial status of coins in a binary string s where 1 represents the gold side facing up and 0 represents the silver side facing up. If it is possible to make the gold-colored side of every coin facing up, return  Yes, otherwise return  No

**Input:**
N = 8, s = "11001100"

**Output**:
Yes

**Explanation:**
Flipping 3rd and 4th coin together and 7th
and 8th coin together will do the task.

**Input:**
N = 8, s = "10010100"

**Output:**
No

**Explanation**
It is not possible to make the gold
colored side of every coin facing up.

### Programming language

- [ ] C
- [ ] C++
- [x] Java
- [ ] Python

I would like to solve this problem in Java language.
Please assign this problem to me under LGMSoC'21.

### PR DESCRIPTION
**Pull request by Karnika06**
# Description

Added Silver and Gold problem which was asked in GeeksforGeeks Job-A-Thon: For Internship Contest.

**Problem statement:**

There are N coins kept in a line. Each coin has two sides - one is colored gold and the other silver. You can flip two adjacent coins any number of times. You need to make the gold-colored side of every coin facing up. You are given the initial status of coins in a binary string s where 1 represents the gold side facing up and 0 represents the silver side facing up. If it is possible to make the gold-colored side of every coin facing up, return  Yes, otherwise return  No

**Input:**
N = 8, s = "11001100"

**Output**:
Yes

**Explanation:**
Flipping 3rd and 4th coin together and 7th
and 8th coin together will do the task.

**Input:**
N = 8, s = "10010100"

**Output:**
No

**Explanation**
It is not possible to make the gold
colored side of every coin facing up.

Fixes #2314 

Please review this PR and merge it.

### CODE REVIEW

**Review by Ayush7614 — CHANGES_REQUESTED** [review]
Delete Other Files

**Comment by Karnika06** [comment]
@Ayush7614 please check or review it once. Have I made the the correct changes?

**Comment by Karnika06** [comment]
@Ayush7614 please check or review it once. Have I made the the correct changes?

**Comment by Amit366** [comment]
@Karnika06 resolve merge conflict

**Pull request closed without merging**
