### PR TITLE
Adding the solution of  Bella ciao(CHFHEIST) on Codechef in C .

### LINKED ISSUE #753: Bella ciao from code chef
# Aim

I want to add the solution to problem Bella ciao from codechef.
Problem link-https://www.codechef.com/JUNE21C/problems/CHFHEIST

### Programming language

- [x] C
- [x] C++
- [x] Java
- [x] Python

### PR DESCRIPTION
**Pull request by Obito2002**
I am LGM-SOC participant and added the C++ code for Bella ciao(CHFHEIST) problem on Codechef.
# Description
Chef is planning a heist in the reserve bank of Chefland. They are planning to hijack the bank for D days and print the money. The initial rate of printing the currency is P dollars per day and they increase the production by Q dollars after every interval of d days. For example, after d days the rate is P+Q dollars per day, and after 2d days the rate is P+2Q dollars per day, and so on. Output the amount of money they will be able to print in the given period.

Fixes #753

Replace `issue_no` with the issue number which is fixed in this PR

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have created a helpful and easy to understand `README.md`
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by Obito2002** [comment]
@Ayush7614 please review the PR and give advice if its correct or wrong.
Its my first PR.

**Comment by Amit366** [comment]
@Obito2002 add test case

**Comment by Amit366** [comment]
@Obito2002 any update?

**Comment by Obito2002** [comment]
I'll add it today

**Comment by Amit366** [comment]
@Obito2002 add it here itself in this code

**Comment by Amit366** [comment]
@Obito2002 since there is no update I am closing it.

**Pull request closed without merging**
