### PR TITLE
7 Segment Display and Traveling Salesman

### LINKED ISSUE #1156: Traveling Salesman Problem using Genetic Algorithm
# Aim

I would like to Contribute Traveling Salesman Problem using Genetic Algorithm under LGMSOC'21 in C++

# Details

Genetic algorithms are heuristic search algorithms inspired by the process that supports the evolution of life. The algorithm is designed to replicate the natural selection process to carry generation, i.e. survival of the fittest of beings

### Programming language

- [ ] C
- [ ] C++
- [ ] Java
- [ ] Python

### PR DESCRIPTION
**Pull request by nishant-giri**
# Description

Added a self-prepared program helpful for Competitive Programming with question and solution in C.
Added the solution of Traveling Salesman Problem using Genetic Algorithm.

Fixes #1156 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by Amit366** [comment]
@nishant-giri remove the other files

**Comment by nishant-giri** [comment]
Yeah, sure. I'll be doing it.

**Comment by Amit366** [comment]
@nishant-giri any update?

**Comment by nishant-giri** [comment]
Yeah, it was updated from my side.

**Comment by Amit366** [comment]
@nishant-giri not yet updated

**Comment by nishant-giri** [comment]
I guess, there was an error. I'll try to make a new PR and close this one.

**Pull request closed without merging**
