### PR TITLE
Added Python Code

### LINKED ISSUE #1618: Majority Element(Leetcode)
## AIM
I will be adding a question in the Leetcode folder [Majority Element](https://leetcode.com/problems/majority-element/).

-  Given an array nums of size n, return the majority element.
The majority element is the element that appears more than ⌊n / 2⌋ times. You may assume that the majority element always exists in the array.

> Test Cases:-

Input: nums = [3,2,3]
Output: 3
Input: nums = [2,2,1,1,1,2,2]
Output: 2

Please Assign me this issue @Amit366  @ravikr126  @Saurabh4626 
### Programming language

- [ ] C
- [ ] C++
- [ ] Java
- [ ] Python

### PR DESCRIPTION
**Pull request by sonamgupta136**
Added #1618

# Description

Added Python Code

Fixes #1618

# Checklist:

- [ ] My code follows the style guidelines(Clean Code) of this project
- [ ] I have performed a self-review of my own code.

### CODE REVIEW

**Comment by sonamgupta136** [comment]
@ravikr126 please review

**Comment by ravikr126** [comment]
For which question .Please add relevant description for pr

**Review by ravikr126 — CHANGES_REQUESTED** [review]
Add relevant comment in code also

**Comment by Amit366** [comment]
@sonamgupta136 add test case

**Comment by sonamgupta136** [comment]
@Amit366 I have made new pr as 1618 majority element python code and closed this pr. As I was new to opensource so I was not able to make changes.Please also review my pr 1621 egg dropping puzzle cpp and 1628 merge k sorted linked list python code.

**Pull request closed without merging**
