### PR TITLE
Java-Solution Delete Node in a Linked List

### LINKED ISSUE #1872: Delete Node in a Linked List(Leetcode)
**Delete Node in a Linked List(Leetcode)**
Write a function to delete a node in a singly-linked list. You will not be given access to the head of the list, instead you will be given access to the node to be deleted directly.

It is guaranteed that the node to be deleted is not a tail node in the list.

 

Example 1:

Input: head = [4,5,1,9], node = 5
Output: [4,1,9]
Explanation: You are given the second node with value 5, the linked list should become 4 -> 1 -> 9 after calling your function.
Example 2:

Input: head = [4,5,1,9], node = 1
Output: [4,5,9]
Explanation: You are given the third node with value 1, the linked list should become 4 -> 5 -> 9 after calling your function.
Example 3:

Input: head = [1,2,3,4], node = 3
Output: [1,2,4]
Example 4:

Input: head = [0,1], node = 0
Output: [1]
Example 5:

Input: head = [-3,5,-99], node = -3
Output: [5,-99]
 

Constraints:

The number of the nodes in the given list is in the range [2, 1000].
-1000 <= Node.val <= 1000
The value of each node in the list is unique.
The node to be deleted is in the list and is not a tail node

### PR DESCRIPTION
**Pull request by 2000shivam659**
Delete Node in a Linked List (JAVA-Solution)

3 Line recursive solution for "Delete Node in a Linked List"

Fixes #1872

Replace #1872  with the issue number which is fixed in this PR

Added Java Solution For This 

_Please delete options that are not relevant._

- [ ] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update
- [ ] Documentation Update

# Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [ ] I have created a helpful and easy to understand `README.md`
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by 2000shivam659** [comment]
merge this #1872

**Comment by 2000shivam659** [comment]
@Amit366 @ravikr126 @Ayush7614
please review this PR and merge it, Thanku.

**Comment by Amit366** [comment]
@2000shivam659 add main function

**Comment by 2000shivam659** [comment]
> @2000shivam659 add main function

It's a leetcode problem.

**Pull request closed without merging**
