### PR TITLE
Solution for Find the K-th Largest Number #530 (Java )

### LINKED ISSUE #530: Find the K-th Largest Number
# Aim

Find the k-th largest number in a sequence of unsorted numbers.

Example:

Input : [8, 7, 2, 3, 4, 1, 5, 6, 9, 0], K = 3 

OutPut: 7

### Programming language

- [x] Java

### PR DESCRIPTION
**Pull request by shantamsultania**
# Description

Fixes #530

## Type of change

# Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by Amit366** [comment]
@shantamsultania remove the other files

**Comment by shantamsultania** [comment]
Done @Amit366

**Comment by Amit366** [comment]
@shantamsultania add the main function

**Comment by shantamsultania** [comment]
hey @Amit366  i have added the main function also please take a look into that

**Pull request merged**
