### PR TITLE
Leetcode #13: Roman to Integer

### PR DESCRIPTION
**Pull request by light1515**
# Description

Solution to LeetCode Question 13: Roman to Integer

Fixes #(issue_no)

Replace `issue_no` with the issue number which is fixed in this PR

## Type of change

_Please delete options that are not relevant._

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Documentation Update

# Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have created a helpful and easy to understand `README.md`
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by light1515** [comment]
Hey @Ayush7614 @Amit366
Kindly review my pull request and merge as soon as you can. Let me know if changes need to be made.

**Comment by Amit366** [comment]
@light1515 issue number??

**Comment by light1515** [comment]
An issue wasn't created for this problem. Should I  create one or should I close the pull request?

**Comment by Amit366** [comment]
@light1515 first create an issue and then PR

**Pull request closed without merging**
