### PR TITLE
Added Solution of Dice Tower in Java

### LINKED ISSUE #1213: Dice Tower question on Codeforces
hi, I want to solve this issue using C++
Please assign this issue to me under LGM-SOC21 and HCSSoC .
Looking forward to contribute here...

Question link: https://codeforces.com/contest/225/problem/A
@Ayush7614

### PR DESCRIPTION
**Pull request by sejal1430**
# Description

This pull request contains the solution to Codeforces **round#139** **problem A Dice Tower** in java. This includes the addition of file named "DiceTower.java" in Codeforces folder.
Link of the problem: https://codeforces.com/contest/225/problem/A

Fixes #1213 

# Checklist:

- [✔ ] My code follows the style guidelines(Clean Code) of this project
- [ ✔] I have performed a self-review of my own code
- [✔ ] My changes generate no new warnings

### CODE REVIEW

**Comment by sejal1430** [comment]
@ravikr126, @Amit366, @Ayush7614 Please review and merge my pull request.

**Comment by Amit366** [comment]
@sejal1430 are u LGM participant??

**Comment by Amit366** [comment]
Add test case

**Comment by sejal1430** [comment]
> @sejal1430 are u LGM participant??

yes

**Comment by sejal1430** [comment]
> Add test case

Ohk, I will add the testcases.

**Comment by sejal1430** [comment]
> Add test case

I have added the test cases to the problem.

**Pull request merged**
