### PR TITLE
Right View of the Binary Tree

### LINKED ISSUE #1008: Right View of a Binary Tree
I want to provide a C++ code for printing "Right View of a Binary Tree".
I am LGM SOC '21 participant and want to provide this code with proper comments and explanations.

@Ayush7614 @ravikr126 @Amit366 @Saurabh4626
Please assign me this issue

### PR DESCRIPTION
**Pull request by somuy24**
# Description

The code for Right View of a Binary Tree has been added in Gfg folder.

Fixes #1008 

## Type of change

- [x] This change requires a documentation update
- [x] Documentation Update

# Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by somuy24** [comment]
@Saurabh4626 @Ayush7614 
Please review my PR request

**Comment by Amit366** [comment]
@somuy24 remove other files

**Comment by somuy24** [comment]
@Amit366 I have deleted other files

**Comment by Amit366** [comment]
@somuy24 its still present

**Comment by Amit366** [comment]
@somuy24 resolve merge conflict

**Pull request closed without merging**
