### PR TITLE
Added smallest positive in leetcode

### LINKED ISSUE #1230: First Missing Positive LeetCode (Hard)
**Additional context**
Q :-Given an unsorted integer array nums, find the smallest missing positive integer.
You must implement an algorithm that runs in O(n) time and uses constant extra space.
### Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python
I want to work on this issue

### PR DESCRIPTION
**Pull request by siddhi-244**
# Description

Added first missing positive element in an array in python.

Fixes #1230 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have created a helpful and easy to understand `README.md`
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

Screenshot_20210626-194209_Chrome

### CODE REVIEW

**Comment by Amit366** [comment]
@siddhi-244 add test case

**Comment by siddhi-244** [comment]
Done @Amit366

**Comment by Amit366** [comment]
@siddhi-244 this is similar to https://www.geeksforgeeks.org/find-the-smallest-positive-number-missing-from-an-unsorted-array-set-2/

**Comment by siddhi-244** [comment]
But sir I have seen it and then practiced on my own @Amit366

**Comment by siddhi-244** [comment]
Ok will make a new pr !

**Comment by Amit366** [comment]
@siddhi-244 all the variables and steps are same and we cannot accept it

**Comment by siddhi-244** [comment]
Ok shall I make a new pr ? @Amit366

**Comment by Amit366** [comment]
Yes

**Pull request closed without merging**
