### PR TITLE
Adding Problem 1526B of Codeforces in C++ and JAVA

### LINKED ISSUE #1129: I Hate 1111 (Problem 1526B)
# Aim

- Solve Problem 1526B of Codeforces

# Details

- This is a problem Under Number theory, I would love to solve this, Please assign me this under LGMSOC21 for C++ and JAVA

### Programming language

- [ ] C
- [ ] C++
- [ ] Java
- [ ] Python

### PR DESCRIPTION
**Pull request by tirth5828**
# Description

Added Problem I Hate 1111 (1526B)  of Codeforces in C++ and JAVA

Fixes #1129 

## Type of change

_Please delete options that are not relevant._

-  New feature (non-breaking change which adds functionality)

# Checklist:

- [ ] My code follows the style guidelines(Clean Code) of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by Amit366** [comment]
@tirth5828 delete other file

**Comment by tirth5828** [comment]
Sorry Sir , But there are two files one for C++ and Other for JAVA.
I am unable to understand which while to delete and why.
Apology if I missed something

**Comment by tirth5828** [comment]
@Amit366 Sir

**Comment by Amit366** [comment]
@tirth5828 if u want points then u have to send separate prs

**Comment by tirth5828** [comment]
Okay sir , Doing it

**Comment by tirth5828** [comment]
Sir I have added 2 new PR with different language code with different title ,  and thus closing this PR . Thanks for helping me out .

**Pull request closed without merging**
