### PR TITLE
added code for mod-equality in c++

### LINKED ISSUE #2301: Codechef problem with Problem Code - Mod Equality
Codechef problem with code - Mod Equality

PROBLEM STATEMENT :-
->> You are given N non-negative integers A1,A2,…,AN. You are allowed to perform following operation any number of times:

Choose any valid index i (1≤i≤N) and a positive integer M>0 and replace Ai with AimodM. That is, replace Ai with its remainder when divided by M, which is a value between 0 and M−1, inclusive.
M does not need to be same between different operations.
Find the minimum number of operations to make all the array elements equal.

Note: Since the input and output are large, prefer using fast input-output methods.
Input Format
The first line contains an integer T - the number of test cases. Then T test cases follow.
The first line of each test case contains an integer N - the size of array.
The second line contains N integers A1,A2,…,AN - the elements of the array.
Output Format
For each test, print one line containing an integer which denotes minimum number of operations performed to make all the elements equal.

Constraints
1≤T≤104
1≤N≤105
0≤Ai≤2⋅109
It is guaranteed that the sum of N over all test cases does not exceed 106.
Sample Input 1 
2
3
2 1 3
3
1 1 3
Sample Output 1 
3
1
Explanation
In first test case, we can make all the elements equal by following operations:

Take i=1 and M=2 and do A1:=A1mod2=0.
Take i=2 and M=1 and do A2:=A2mod1=0.
Take i=3 and M=3 and do A3:=A3mod3=0.
After these 3 operations we have all the elements equal to zero.
In second test case, we can perform following operation:

Choose i=3 and M=2 and do A3:=A3mod2=1.
After this operation all the elements are 1.

- >> What is the objective of the Script

The solution to the problem in O(n) Time complexity.

LINK TO THE PROBLEM :- https://www.codechef.com/COOK131B/problems/MODEQUAL

### Programming language

- [ ] C
- [✔ ] C++
- [ ] Java
- [ ] Python

### PR DESCRIPTION
**Pull request by inimitable034**
# Description

This code is the solution for the mod equality , asked in the codechef cookoff competition.
The code has functions and solutions described as well.
It is an O(nlogn) time complexity approach.

Fixes #2301 

Test cases:--

Sample Input 1 
2
3
2 1 3
3
1 1 3
Sample Output 1 
3
1
Explanation
In first test case, we can make all the elements equal by following operations:

Take i=1 and M=2 and do A1:=A1mod2=0.
Take i=2 and M=1 and do A2:=A2mod1=0.
Take i=3 and M=3 and do A3:=A3mod3=0.
After these 3 operations we have all the elements equal to zero.
In second test case, we can perform following operation:

Choose i=3 and M=2 and do A3:=A3mod2=1.
After this operation all the elements are 1.

# Checklist:

My code follows the style guidelines(Clean Code) of this project
 I have performed a **self-review** of my own code
 I have commented my code, particularly in hard-to-understand areas
 I have created a helpful and easy to understand `README.md`
 I have made corresponding changes to the documentation
 My changes generate no new warnings
 I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by sameeksharl — COMMENTED** [review]
@inimitable034 add proper extension , .cpp

**Comment by inimitable034** [comment]
> @inimitable034 add proper extension , .cpp

i am sorry for that 
Actually i also dont know how it got converted into t.xt format from .cpp
I have made the changes though

**Comment by Amit366** [comment]
@inimitable034 delete the other file

**Comment by inimitable034** [comment]
Done sir @Amit366 
Deleted unwanted files from the commit.

**Comment by inimitable034** [comment]
This contribution is done my me under LGM-SOC 2021
@ravikr126 @Amit366

**Comment by Amit366** [comment]
@inimitable034 add test cases.

**Pull request merged**
