### PR TITLE
Added Check Dead in Binary Search Tree inside GFG folder

### PR DESCRIPTION
**Pull request by SNEHAL311998**
# Description
Given a Binary Search Tree that contains positive integer values greater than 0. The task is to check whether the BST contains a dead end or not. Here Dead End means, we are not able to insert any integer element after that node.
Please include a summary of the change and which issue is fixed. List any dependencies that are required for this change.
<br>
check_dead

# Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by SNEHAL311998** [comment]
This question is from GFG which I found difficult to solve but somehow managed to solve and I think it would be helpful for other students as well since I have written the code clearly

**Comment by SNEHAL311998** [comment]
# Distance between two nodes in Binary Search Tree
nodedistancebst
<br>
Find the distance between two keys in a binary tree, no parent pointers are given. The distance between two nodes is the minimum number of edges to be traversed to reach one node from another.
<br>

**Comment by SNEHAL311998** [comment]
There are two files that i have committed please go through it

**Comment by Amit366** [comment]
@SNEHAL311998 mention the issue number

**Pull request closed without merging**
