### PR TITLE
Added Median of two sorted arrays(Leetcode)

### LINKED ISSUE #1422: Median of two sorted arrays (LEETCODE HARD)
# Aim

image

# Details

- What the features will your script have

### Programming language

- [ ] C
- [ ] C++
- [ ] Java
- [ ] Python

### PR DESCRIPTION
**Pull request by Ananya-Misra**
# Description

Added code for Median of two sorted arrays.

Fixes #1422

Replace `issue_no` with the issue number which is fixed in this PR

## Type of change

_Please delete options that are not relevant._

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [x] Documentation Update

# Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have created a helpful and easy to understand `README.md`
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by Amit366** [comment]
@Ananya-Misra add test case

**Comment by Amit366** [comment]
Since there is no update I am closing this PR

**Comment by Ananya-Misra** [comment]
@Amit366 can you reopen this PR I didn't saw the message until today. I will make the required changes by today itself.

**Comment by Amit366** [comment]
@Ananya-Misra sorry it cannot be reopened. But if u want u can send new PR

**Pull request closed without merging**
