### PR TITLE
Bottom View of a Binary Tree

### LINKED ISSUE #1006: Bottom View of a Binary Tree
I want to provide a C++ code for printing "Bottom View of a Binary Tree".
I am LGM SOC '21 participant and want to provide this code with proper comments and explanations.

@Ayush7614 @ravikr126 @Amit366 @Saurabh4626 
Please assign me this issue

### PR DESCRIPTION
**Pull request by somuy24**
# Description
The code for Bottom View of a Binary Tree has been added in Gfg folder.

Fixes #1006

## Type of change

- [x] This change requires a documentation update
- [x] Documentation Update

# Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by somuy24** [comment]
@Saurabh4626 
I have added the code of Bottom view of the Binary Tree.
Please review the changes.

**Comment by Amit366** [comment]
@somuy24 delete the exe file

**Comment by somuy24** [comment]
@Amit366 I have deleted the file, please review the changes.

**Comment by Amit366** [comment]
@somuy24 its not deleted

**Comment by somuy24** [comment]
@Amit366 I have deleted the

**Comment by somuy24** [comment]
@Amit366 I have deleted the .exe file, Please review it.

**Comment by Amit366** [comment]
@somuy24 its not deleted. If u r facing any problem then send another PR.

**Comment by somuy24** [comment]
@Amit366 sorry for the inconvenience, now I have finally deleted it.

**Comment by somuy24** [comment]
@Amit366 sorry for the inconvenience, now I have finally deleted it.

**Pull request merged**
