### PR TITLE
Added the code of [Leetcode] TREE : Construct Binary Tree from Preorder and Inorder Traversal in JAVA Issue 1344

### LINKED ISSUE #1344: [Leetcode] TREE : Construct Binary Tree from Preorder and Inorder Traversal in JAVA
**Explanation**
Given two integer arrays preorder and inorder where preorder is the preorder traversal of a binary tree and inorder is the inorder traversal of the same tree, construct and return the binary tree.

**Example 1**
Input: preorder = [3,9,20,15,7], inorder = [9,3,15,20,7]
Output: [3,9,20, null, null, 15,7]

**Example 2:**
Input: preorder = [-1], inorder = [-1]
Output: [-1]

**Additional context**
Hey @Amit366  I want to add this question(in JAVA) in the " Daily-Coding-DS-ALGO-Practice/Leetcode ". 

- https://leetcode.com/problems/construct-binary-tree-from-preorder-and-inorder-traversal/
- LGM-SOC'21

### Programming language

- [ ] C
- [ ] C++
- [x] Java
- [ ] Python

### PR DESCRIPTION
**Pull request by geetika1723**
# Description

Constructed A Binary Tree from Preorder and Inorder Traversal in Java Language.

Fixes #1344

## Type of change

- [ ] New feature (non-breaking change which adds functionality)

# Checklist:

- [ ] My code follows the style guidelines(Clean Code) of this project
- [ ] I have performed a self-review of my own code
- [ ] My changes generate no new warnings

### CODE REVIEW

**Comment by geetika1723** [comment]
@Amit366 Kindly review the file.I have updated my code by adding main function and comments where ever required.

**Comment by Amit366** [comment]
@geetika1723 add test case

**Comment by Amit366** [comment]
Since no update, I am closing it.

**Comment by geetika1723** [comment]
@Amit366 Due to some issues I was unable to edit this file. Hence, created a new pull request .
https://github.com/Ayush7614/Daily-Coding-DS-ALGO-Practice/pull/2063

Kindly review it .

**Pull request closed without merging**
