### PR TITLE
Adding Solutions to Problems on Hackerrank

### LINKED ISSUE #8: Added questions on Algorithms

### PR DESCRIPTION
**Pull request by VinayakMohite4040**
# Description

Adding solutions to problems under the section of Practice->Problem Solving

Fixes #8 #9

## Type of change

_Please delete options that are not relevant._

- [x] Bug fix (non-breaking change which fixes an issue)

# Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by VinayakMohite4040** [comment]
Kindly consider this PR @Ayush7614

**Comment by VinayakMohite4040** [comment]
Kindly consider this PR...
@Ayush7614  @Amit366 @Saurabh4626 @ravikr126

**Comment by ravikr126** [comment]
You added alot of solutins .We need quality solutions not quantity solutions.@VinayakMohite4040

**Comment by VinayakMohite4040** [comment]
@ravikr126 I added only 5 solutions per day and tried creating a PR every day.. As my previous PR wasn't considered for merging, hence the changes thereafter accumulated in a single PR. Hence it looks like I am trying to add many solutions in a single PR.
Anyways, thanks to @ravikr126 , @Ayush7614, @Amit366, @Saurabh4626 for feedback. All the best for the future of this repo.

**Pull request closed without merging**
