### PR TITLE
Sliding Window Maximum Using C++

### PR DESCRIPTION
**Pull request by Garg17a**
Given an array of integers nums, there is a sliding window of size k which is moving from the very left of the array to the very right. You can only see the k numbers in the window. Each time the sliding window moves right by one position.

Input: nums = [1,3,-1,-3,5,3,6,7], k = 3
Output: [3,3,5,5,6,7]

class Solution {
public:
    vector<int> maxSlidingWindow(vector<int>& nums, int k) {
        vector<int> res;
        deque<int> q;                 //double ended queue to keep track of decreasing elements
        for(int i=0;i<k;i++) {        //initially run the loop for firts k numbers in the array
            while(!q.empty() && nums[q.back()]<=nums[i])            //this is the main condition of removing elements from the queue that are less than the current element because they become useless for us as they will never become maximum.
                q.pop_back();
            q.push_back(i);           //Push elements at the back of the queue
        }
        for(int i=k;i<nums.size();i++) {
            res.push_back(nums[q.front()]);             //The first element of the queue will always be the index of the maximum number
            while(!q.empty() && q.front()<=i-k)              //Remove the elements from the front if they fall out of range i.e if they exceed the window size
                q.pop_front();
            while(!q.empty() && nums[q.back()]<nums[i])
                q.pop_back();
            q.push_back(i);
        }
        res.push_back(nums[q.front()]);
        return res;
    }
};

### CODE REVIEW

**Comment by Amit366** [comment]
@Garg17a where is the code???

**Comment by Garg17a** [comment]
> @Garg17a where is the code???

Given an array of integers nums, there is a sliding window of size k which is moving from the very left of the array to the very right. You can only see the k numbers in the window. Each time the sliding window moves right by one position.

Input: nums = [1,3,-1,-3,5,3,6,7], k = 3
Output: [3,3,5,5,6,7]

class Solution {
public:
vector maxSlidingWindow(vector& nums, int k) {
vector res;
deque q; //double ended queue to keep track of decreasing elements
for(int i=0;i<k;i++) { //initially run the loop for firts k numbers in the array
while(!q.empty() && nums[q.back()]<=nums[i]) //this is the main condition of removing elements from the queue that are less than the current element because they become useless for us as they will never become maximum.
q.pop_back();
q.push_back(i); //Push elements at the back of the queue
}
for(int i=k;i<nums.size();i++) {
res.push_back(nums[q.front()]); //The first element of the queue will always be the index of the maximum number
while(!q.empty() && q.front()<=i-k) //Remove the elements from the front if they fall out of range i.e if they exceed the window size
q.pop_front();
while(!q.empty() && nums[q.back()]<nums[i])
q.pop_back();
q.push_back(i);
}
res.push_back(nums[q.front()]);
return res;
}
};

**Comment by Amit366** [comment]
@Garg17a r u in the slack channel and did u attend yesterday's meeting??

**Comment by Garg17a** [comment]
> @Garg17a r u in the slack channel and did u attend yesterday's meeting??

yes

**Comment by Amit366** [comment]
Then what was taught to u?? @Garg17a

**Comment by Amit366** [comment]
Not to paste the code in comments section

**Pull request closed without merging**
