### PR TITLE
Added Segment tree implementation in Algorithm section

### LINKED ISSUE #847: Segment tree Implementation
Want to add c++ file , on implementation of segment tree on given array.
And this will go under Algorithm section

### Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

### PR DESCRIPTION
**Pull request by akash435**
# Description
Added the segment tree implementation in algorithm section.
The segment tree is basically used in handling range sum, and update query.

Fixes #847

## Type of change

_Please delete options that are not relevant._

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Documentation Update

# Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [ ] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have created a helpful and easy to understand `README.md`
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

Following is the screenshots of output of range sum query,

### CODE REVIEW

**Comment by akash435** [comment]
created a pr for adding implementation of Segment Tree in algorithm section.

**Comment by Amit366** [comment]
@akash435 add test cases

**Comment by akash435** [comment]
@Amit366 , added test case please check it

**Comment by Amit366** [comment]
@akash435 there is no segment tree folder

**Comment by Amit366** [comment]
Place it in Data structure tree folder

**Comment by akash435** [comment]
@Amit366 , changes done, please check it.

**Pull request merged**
