### PR TITLE
added median of 2 sorted array

### LINKED ISSUE #340: Median Of two sorted Arrays
1. Problem link: https://practice.geeksforgeeks.org/problems/median-of-two-sorted-arrays1618/1/?track=P100-Searching#
2. Problem: Given Given two sorted arrays of sizes N and M respectively. The task is to find the median of the two arrays when they get merged.
3. Platform: gfg
4. Language: C++

### PR DESCRIPTION
**Pull request by nikhil00shinde**
# Description
It is about the median of 2 sorted arrays.
I have completed issue number #340. Please accept the pull request. 

Fixes #340

Replace `#340` with the issue number which is fixed in this PR

## Type of change

# Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Comment by Amit366** [comment]
@nikhil00shinde add main function

**Comment by nikhil00shinde** [comment]
> 
> 
> @nikhil00shinde add main function

@Amit366 In the question they have given only to fill the function.

**Comment by Amit366** [comment]
@nikhil00shinde u have to write the main function.

**Comment by Amit366** [comment]
@nikhil00shinde since there is no update I am closing this

**Pull request closed without merging**
