### PR TITLE
1618 majority element pythoncode

### LINKED ISSUE #1618: Majority Element(Leetcode)
## AIM
I will be adding a question in the Leetcode folder [Majority Element](https://leetcode.com/problems/majority-element/).

-  Given an array nums of size n, return the majority element.
The majority element is the element that appears more than ⌊n / 2⌋ times. You may assume that the majority element always exists in the array.

> Test Cases:-

Input: nums = [3,2,3]
Output: 3
Input: nums = [2,2,1,1,1,2,2]
Output: 2

Please Assign me this issue @Amit366  @ravikr126  @Saurabh4626 
### Programming language

- [ ] C
- [ ] C++
- [ ] Java
- [ ] Python

### PR DESCRIPTION
**Pull request by sonamgupta136**
# Description

Added Python Code For Majority Element (Leetcode).

Fixes #1618 

## Type of change

_Please delete options that are not relevant._

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Documentation Update

# Checklist:

- [ ] My code follows the style guidelines(Clean Code) of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have created a helpful and easy to understand `README.md`
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings

### CODE REVIEW

**Comment by sonamgupta136** [comment]
@ravikr366 please review now.

**Comment by Amit366** [comment]
@sonamgupta136 delete the file which is not a part of this PR

**Comment by Amit366** [comment]
@sonamgupta136 add main function

**Comment by Amit366** [comment]
@sonamgupta136 resolve merge conflict

**Comment by sonamgupta136** [comment]
@Amit366  #1618 please review now

**Pull request merged**
