### PR TITLE
Longest Consecutive Sequence using Python

### LINKED ISSUE #1222: Longest Consecutive Sequence
**AIM**
Given an unsorted array of integers nums, return the length of the longest consecutive elements sequence.

Please Assign me under LGM SOC .I will be solving in C++ language.

### Programming language

- [ ] C
- [ ] C++
- [ ] Java
- [ ] Python

### PR DESCRIPTION
**Pull request by Ashu-1309**
# Description

Please include a summary of the change and which issue is fixed. List any dependencies that are required for this change.

Fixes #1222

## Type of change
I have written the code in python.

_Please delete options that are not relevant._

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Documentation Update

# Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have created a helpful and easy to understand `README.md`
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by Ashu-1309** [comment]
I have uploaded the code of Longest Consecutive  sequence using python.

**Comment by kamleshjoshi8102** [comment]
@Saurabh4626 @ravikr126 @Ayush7614 Please Assign me this issue. I will solve it in java or C++
LGM-SOC'21

**Review by Saurabh4626 — CHANGES_REQUESTED** [review]
your code is giving TLE

**Comment by Ashu-1309** [comment]
Will my code merge ???

**Comment by Ashu-1309** [comment]
It is working fine in online Complier !!!


Screenshot_2021-06-21-23-50-42-870_com android chrome

**Comment by Ashu-1309** [comment]
What changes should I make in order to run the program successfully .

**Comment by Ashu-1309** [comment]
Can you please tell me what I have to do now ???

**Comment by Ashu-1309** [comment]
The code is working fine Pycharm ide

LCS

**Comment by Amit366** [comment]
@Ashu-1309 it is fine. just mention the issue number and also add test cases to the code.

**Comment by Ashu-1309** [comment]
What I have to add in the test case ???

**Comment by Amit366** [comment]
@Ashu-1309 mention the issue number and also go through the PR #1316 for the test case

**Comment by Ashu-1309** [comment]
Done with all the stuffs. Can you please verify it .

**Comment by Amit366** [comment]
@Ashu-1309 where is the test case?

**Comment by Amit366** [comment]
@Ashu-1309 bro do u know what is a test case?? I said u to refer to the PR above

**Comment by Ashu-1309** [comment]
No I don't have any idea about test case .

**Comment by Amit366** [comment]
@Ashu-1309 take a sample input and show the output. That's why I asked u to look at the Pr #1316

**Comment by Ashu-1309** [comment]
I have explained the code using the input only. In the proper sequence. Defining all the value that are taken .

**Pull request merged**
