### PR TITLE
Added the Conversion of Roman Number to Integer in GFG which I have Practiced a few days ago (issue number #573)

### PR DESCRIPTION
**Pull request by geekySapien**
…ed few days ago

# Description

Please include a summary of the change and which issue is fixed. List any dependencies that are required for this change.

Fixes #(issue_no)

Replace `issue_no` with the issue number which is fixed in this PR

## Type of change

_Please delete options that are not relevant._

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Documentation Update

# Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by geekySapien** [comment]
Issue no:  #573
I am Riya Dhanwani! I have added a C++ solution for :
Best Time to Buy and Sell Stock which is a standard question asked by many of the companies.
I practiced it from Love Babbar cheat sheet. 
My code is easy to understand and is a tested code and works absolutely fine.

**Comment by geekySapien** [comment]
Sir there is a typo, I have contributed for the "Conversion of Roman Number to Integer" from GFG which I practice a few days ago

**Comment by Amit366** [comment]
@geekySapien the issue name and file name doesn't match

**Comment by geekySapien** [comment]
Sir, I have edited the Issue Name. Could you please review it 
Thanks

**Comment by Amit366** [comment]
@geekySapien mention the issue number

**Comment by geekySapien** [comment]
Issue no: #573
Question: Conversion of Roman Number to Integer in GFG  (issue number #573).
Added. 
Thank you

**Comment by Amit366** [comment]
@geekySapien have u opened an issue or directly sent the pull request??

**Comment by geekySapien** [comment]
Sir, I directly sent the pull request and issue no #573 appeared when made the pull request

**Comment by Amit366** [comment]
@geekySapien it is not allowed. First create the issue and then send the pull request

**Pull request closed without merging**
