### PR TITLE
Preparata_Sorting_Algorithm.py

### LINKED ISSUE #1153: Preparata Algorithm
# Aim

I would Like to contribute Preparata Algorithm (hard) under LGMSOC'21 in C++

# Details

Preparata’s algorithm is a recursive Divide and Conquer Algorithm where the rank of each input key is computed and the keys are outputted according to their ranks.

### Programming language

- [ ] C
- [ ] C++
- [ ] Java
- [ ] Python

### PR DESCRIPTION
**Pull request by kamleshjoshi8102**
# Description

Added Preparata_Sorting_Algorithm.py

Fixes #1153 

Replace `issue_no` with the issue number which is fixed in this PR

## Type of change

_Please delete options that are not relevant._

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update
- [x] Documentation Update

# Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by Amit366** [comment]
@kamleshjoshi8102 add test cases

**Comment by kamleshjoshi8102** [comment]
@Amit366 I have added output at last of code and input is in that code

**Comment by Amit366** [comment]
@kamleshjoshi8102 this is similar to https://www.geeksforgeeks.org/preparata-algorithm/

**Comment by Amit366** [comment]
@kamleshjoshi8102 this is ur 3rd time that u r sending plagiarised code

**Comment by kamleshjoshi8102** [comment]
> @kamleshjoshi8102 this is ur 3rd time that u r sending plagiarised code

I don't have any problem if you close this issue, sir!

I submitted because you haven't checked many codes which are plagiarised and still they are on top : )


And for your info sir, how can a code be plagiarized if i have mentioned the link of that code ?

**Comment by kamleshjoshi8102** [comment]
> @kamleshjoshi8102 this is ur 3rd time that u r sending plagiarised code

I don't have any problem if you close this issue, sir!

I submitted because you haven't checked many codes which are plagiarised and still they are on top : )


And for your info sir, how can a code be plagiarized if I have mentioned the link of that code?

**Comment by Amit366** [comment]
@kamleshjoshi8102 just mention the PRs which are plagiarized. And for your kind information each and every line is same as https://www.geeksforgeeks.org/preparata-algorithm/.

**Pull request closed without merging**
