### PR TITLE
Updated Shell Sort

### PR DESCRIPTION
**Pull request by Atif0604**
# Description
Added Shell Sort in Java Language
Added Kruskal's Algorithm in C Language

#Fixes #(issue_no)
Shell Sort in C++ #675 
Kruskal's Algorithm #681

## Type of change

_Please delete options that are not relevant._

- [ ✔️ ] New feature (non-breaking change which adds functionality)

# Checklist:

- [✔️  ] My code follows the style guidelines(Clean Code) of this project
- [ ✔️ ] I have performed a self-review of my own code
- [ ✔️ ] I have commented my code, particularly in hard-to-understand areas
- [ ✔️ ] I have created a helpful and easy to understand `README.md`
- [ ] I have made corresponding changes to the documentation
- [ ✔️ ] My changes generate no new warnings
- [ ✔️ ] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by Atif0604** [comment]
@Amit366 Please review it

**Comment by Ayush7614** [comment]
@Atif0604 plss remove Kruskal Algo File

**Comment by Atif0604** [comment]
Done @Ayush7614

**Comment by Amit366** [comment]
@Atif0604 this is similar to https://tutorialspoint.dev/algorithm/sorting-algorithms/shellsort

**Pull request closed without merging**
