### PR TITLE
Stack Implementation using array

### LINKED ISSUE #195: Implementing stack using array
In array implementation, the stack will be formed by using an array and the operations regarding the stack like push and pop will be performed using arrays.

I want to work on this issue in C++ language.

I request @Ayush7614 to assign me this issue for LGM SOC'21.

### PR DESCRIPTION
**Pull request by drishika2002**
# Description

In stack implementation using an array, the stack is formed by using an array and the operations related to the stack like push and pop are performed using arrays.

Fixes #195 

Replace `issue_no` with the issue number which is fixed in this PR

## Type of change

_Please delete options that are not relevant._

- [✔] New feature (new code added)

# Checklist:

- [✔] My code follows the style guidelines(Clean Code) of this project
- [✔] I have performed a self-review of my own code
- [✔] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by toth2000 — CHANGES_REQUESTED** [review]
The code looks good but the `peek()` method is missing.

**Comment by drishika2002** [comment]
> The code looks good but the `peek()` method is missing.

Sure sir, I will add it

**Comment by drishika2002** [comment]
@toth2000 Please review the code. I have made the required changes.

**Review by toth2000 — APPROVED** [review]
Looks good to me.

**Pull request merged**
