### PR TITLE
Generic Swaps using Templates

### LINKED ISSUE #271: Generic Swap using Templates
**Describe the solution you'd like**
Making an algorithm that generally swap any Integer or Character

### Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

### PR DESCRIPTION
**Pull request by agamgupta2015**
# Description

Please include a summary of the change and which issue is fixed. List any dependencies that are required for this change.

Fixes #271

## Type of change
- [x] New feature (non-breaking change which adds functionality)
# Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by agamgupta2015** [comment]
Please Review

**Comment by Amit366** [comment]
@agamgupta2015 please place it inside data structure folder

**Comment by Amit366** [comment]
@agamgupta2015 do u use any text editor??

**Comment by agamgupta2015** [comment]
no only notepad

**Comment by agamgupta2015** [comment]
labels are also not assign to my program

**Comment by Ayush7614** [comment]
@agamgupta2015 Please place it in Data Structurs Folder

**Comment by agamgupta2015** [comment]
That what i am asking please tell me how to do it now

**Pull request closed without merging**
