### PR TITLE
Detect Cycle in a Directed Graph code

### LINKED ISSUE #1579: Detect Cycle in a Directed Graph
# Aim

To Detect Cycle in a given Directed Graph.

# Details
Given a directed graph, check whether the graph contains a cycle or not. Your function should return true if the given graph contains at least one cycle, else return false.

### Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

@Ayush7614 bhiya please assign this issue to me.

### PR DESCRIPTION
**Pull request by Surajvatsya**
# Description

To Detect Cycle in a given Directed Graph.
Given a directed graph, check whether the graph contains a cycle or not. Your function should return true if the given graph contains at least one cycle, else return false.

Fixes #1579

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have created a helpful and easy to understand `README.md`
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

Screenshot (3246)

### CODE REVIEW

**Comment by Amit366** [comment]
@Surajvatsya remove other files

**Comment by Surajvatsya** [comment]
@Amit366 bhiya done.

**Comment by Amit366** [comment]
@Surajvatsya delete the exe file

**Comment by Amit366** [comment]
Since no update I am closing it.

**Pull request closed without merging**
