### PR TITLE
Diagonal Traversal Solution in python of binary tree

### LINKED ISSUE #1398: Diagonal Traversal of Binary Tree
I want to provide a C++ code for printing diagonal traversal of a binary tree.
diagonal

Diagonal Traversal of binary tree : 
 8 10 14 3 6 7 13 1 4

I am LGM SOC'21 participant and want to provide this code with proper comments and explanation.

@Ayush7614 @Amit366 @Saurabh4626 @ravikr126 Please assign me this issue.

### PR DESCRIPTION
**Pull request by SrihariTadala**
# Description

Please include a summary of the change and which issue is fixed. List any dependencies that are required for this change.

Fixes #1398

Replace `issue_no` with the issue number which is fixed in this PR

## Type of change

_Please delete options that are not relevant._

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Documentation Update

# Checklist:

- [ ] My code follows the style guidelines(Clean Code) of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have created a helpful and easy to understand `README.md`
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by Amit366** [comment]
@SrihariTadala comment out the parts which are not a part of the program

**Comment by Amit366** [comment]
@SrihariTadala don't u know how to comment in python??  u can u ''' to comment

**Review by Ayush7614 — CHANGES_REQUESTED** [review]
Doing ASAP @SrihariTadala until i am closing your PR

**Comment by Amit366** [comment]
Since no update I am closing it

**Pull request closed without merging**
