### PR TITLE
Added the program of reversing words in a string

### LINKED ISSUE #1638: Reversing words in a String-leetcode
AIM
Want to add solution the "Reversing words in  a String".
Kindly assign me this problem I want to add solution to this problem in C++.
Link To the problem:-https://leetcode.com/problems/reverse-words-in-a-string/

DETAILS
Given an input string s, reverse the order of the words.

A word is defined as a sequence of non-space characters. The words in s will be separated by at least one space.

Return a string of the words in reverse order concatenated by a single space.
Example 1:

Input: s = "the sky is blue"
Output: "blue is sky the"
Example 2:

Input: s = "  hello world  "
Output: "world hello"
Explanation: Your reversed string should not contain leading or trailing spaces.

### Programming language

- [ ] C
- [ ] C++
- [ ] Java
- [ ] Python

### PR DESCRIPTION
**Pull request by yellowberard**
# Description

Added a program for reversing the words in a string

Fixes #1638 

Replace `issue_no` with the issue number which is fixed in this PR

## Type of change

_Please delete options that are not relevant._

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [ ] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have created a helpful and easy to understand `README.md`
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by yellowberard** [comment]
@ravikr126 Kindly Review my PR

**Comment by yellowberard** [comment]
@ravikr126 @Ayush7614 please review my PR

**Comment by yellowberard** [comment]
@chicken-biryani @Amit366  Kindly review my PR

**Review by chicken-biryani — COMMENTED** [review]
Add the time and space complexity.

**Comment by Amit366** [comment]
@yellowberard add the main function

**Comment by yellowberard** [comment]
@Amit366 Sir, I have done this question on Leetcode  and the main function is not provided by them. So,  I can't add main function.

**Comment by yellowberard** [comment]
@chicken-biryani  Ma'am, I have added the Time complexity and Space Complexity.

**Comment by yellowberard** [comment]
@Amit366 @chicken-biryani @ravikr126  Please review my PR

**Comment by Amit366** [comment]
@yellowberard you have to add the main function since this is not leetcode , this is open source.

**Comment by Amit366** [comment]
Since no update I am closing it

**Pull request closed without merging**
