### PR TITLE
Coding bat

### PR DESCRIPTION
**Pull request by utkarsh1311**
# Description

Added solutions of the Warmup -1 in Java section of CodingBat.

## Type of change

_Please delete options that are not relevant._

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update
- [x] Documentation Update

# Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by Amit366** [comment]
@utkarsh1311 are u a part of LGMSOC?? If yes then first get assigned and then send PR

**Comment by utkarsh1311** [comment]
Yes I am a participant in LGMSOC.

**Comment by utkarsh1311** [comment]
Should I delete this PR and open another after starting an issue and getting assigned??

**Comment by Amit366** [comment]
Yes

**Pull request closed without merging**
