### PR TITLE
#286 Adjacent Difference Algo

### LINKED ISSUE #286: Adjacent Difference Algorithm
**Describe the solution you'd like**
The adjacent_difference algo produces a new sequence in which each element is difference between adjacent elements in original sequence.

### Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

### PR DESCRIPTION
**Pull request by agamgupta2015**
Fixes #286 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by agamgupta2015** [comment]
Please Review

**Comment by Amit366** [comment]
@agamgupta2015 place ur file in appropriate folder

**Comment by agamgupta2015** [comment]
ok

**Comment by agamgupta2015** [comment]
#286 pull request folder changed

**Comment by agamgupta2015** [comment]
Check pull request #519

**Pull request closed without merging**
