### PR TITLE
Added gas station problem in leetcode section

### LINKED ISSUE #2348: Gas station problem using greedy algorithm
# Aim

-I want to add one good question of greedy algorithm. This is the gas station problem.

There are n gas stations along a circular route, where the amount of gas at the ith station is gas[i].

You have a car with an unlimited gas tank and it costs cost[i] of gas to travel from the ith station to its next (i + 1)th station. You begin the journey with an empty tank at one of the gas stations.

Given two integer arrays gas and cost, return the starting gas station's index if you can travel around the circuit once in the clockwise direction, otherwise return -1. If there exists a solution, it is guaranteed to be unique.

Input: gas = [1,2,3,4,5], cost = [3,4,5,1,2]
Output: 3
Explanation:
Start at station 3 (index 3) and fill up with 4 unit of gas. Your tank = 0 + 4 = 4
Travel to station 4. Your tank = 4 - 1 + 5 = 8
Travel to station 0. Your tank = 8 - 2 + 1 = 7
Travel to station 1. Your tank = 7 - 3 + 2 = 6
Travel to station 2. Your tank = 6 - 4 + 3 = 5
Travel to station 3. The cost is 5. Your gas is just enough to travel back to station 3.
Therefore, return 3 as the starting index.

# Details

- I will use greedy algorithm. This is the graph of gas quantity in fuel tank.
-
image

### Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

### PR DESCRIPTION
**Pull request by nik464**
# Description

I have fixed gas station problem and added in leetcode section. 
Fixes #2348 

## Type of change

_Please delete options that are not relevant._

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Documentation Update

# Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have created a helpful and easy to understand `README.md`
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by nik464** [comment]
I have provided the solution as well as explanation to leetcode gas station problem.

**Comment by Amit366** [comment]
@nik464 add the code in proper folder

**Comment by nik464** [comment]
i have now added in right place . In leetcode c++ folder.

**Review by Ayush7614 — APPROVED** [review]

**Review by Ayush7614 — CHANGES_REQUESTED** [review]
Make changes properly

**Comment by nik464** [comment]
what change i have to do in the code? I had added it in leetcode c++ folder. Anything else.

**Comment by Amit366** [comment]
@nik464 main function?

**Pull request merged**
