### PR TITLE
Codeforces 112A c++ solution

### PR DESCRIPTION
**Pull request by AmanAssassin**
# Description

Please include a summary of the change and which issue is fixed. List any dependencies that are required for this change.

Fixes #(2373)

solved the codeforces question no 112A named Petya and strings in language C++
# Checklist:

- [ ] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have created a helpful and easy to understand `README.md`
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by pandapritish25** [comment]
i can easily solve the bug

**Comment by pandapritish25** [comment]
This can be done by taking strings so that it is more understable many of them maynot get the ascii values of these

**Review by pandapritish25 — CHANGES_REQUESTED** [review]
This can be done by taking strings so that it is more understable many of them maynot get the ascii values of these

**Comment by pandapritish25** [comment]
#include<bits/stdc++.h>
using namespace std;
int main()
{
	string a,b;
	cin >> a >> b;
	for(int i=0;i<a.size();i++)
	{
		a[i]=tolower(a[i]);
		b[i]=tolower(b[i]);
	}
	if(a==b)
	{
		cout << "0" << endl;
	}
	else
	{
		for(int i=0;i<a.size();i++)
		{
			if(a[i] < b[i])
			{
				cout << "-1" << endl;
				break;
			}
			if(a[i] > b[i])
			{
				cout << "1" << endl;
				break;
			}
		}
	}
	return 0;
}

**Comment by AmanAssassin** [comment]
It can be solved but the approach of ASCII value came first so did with that only .

**Pull request closed without merging**
