### PR TITLE
The Skyline Problem from Leetcode

### LINKED ISSUE #1613: The skyline Problem (hard)
**Is your feature request related to a problem? Please describe.**
I would like to add the solution to the skyline problem from leetcode 
Link to the problem -
https://leetcode.com/problems/the-skyline-problem/

### Programming language

- [ ] C
- [x] C++
- [x] Java
- [ ] Python

### PR DESCRIPTION
**Pull request by Khushi-agarwal**
# Description

Included the code in JAVA Language
Fixes #1613 

## Type of change

_Please delete options that are not relevant._
- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by Amit366** [comment]
@Khushi-agarwal add main function

**Comment by Khushi-agarwal** [comment]
@Amit366 added the main function.

**Review by ravikr126 — APPROVED** [review]

**Comment by Khushi-agarwal** [comment]
@ravikr126 kindly add the labels.

**Comment by Khushi-agarwal** [comment]
@ravikr126 it's a level 3 issue.

**Comment by Khushi-agarwal** [comment]
@ravikr126 kindly look into the label as it was of level 3 and not of 2.

**Comment by Khushi-agarwal** [comment]
Thank you:) @ravikr126

**Pull request merged**
