### PR TITLE
Paratha-roti problem

### LINKED ISSUE #181: Paratha-Roti Problem
# Aim
There are P parathas to be packed . The stall has N cooks , each cook with rank R can cook 1 parantha in first R minutes , next parantha in 2R minutes and so on. Calculate the minimum time to get order done.

# Details
Constraints- 
P<=1000, 
N<=50, 
1<=R<=8

Sample test case-
Input-
10
4 
1 2 3 4

Output-
12

### Programming language

- [ ] C
- [X] C++
- [ ] Java
- [ ] Python

### PR DESCRIPTION
**Pull request by codebuzzer01**
# Description

An optimized solution of Roti-Parata problem using Binary Search Technique.

# Fixes  #181

Type of change

_Please delete options that are not relevant._

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Documentation Update

# Checklist:

- [X] My code follows the style guidelines(Clean Code) of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have created a helpful and easy to understand `README.md`
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

## 
Screenshot (310)

### CODE REVIEW

**Comment by Amit366** [comment]
@codebuzzer01 is it a sorting or searching algo??

**Comment by Amit366** [comment]
iF not then place it in the folder of its corresponding website folder

**Comment by codebuzzer01** [comment]
@Amit366  Yes, It performs binary search , that's why I have placed it in Searching and Sorting Algo folder

**Comment by Amit366** [comment]
@codebuzzer01 but it doesn't perform any searching

**Comment by Amit366** [comment]
It finds the time

**Comment by Amit366** [comment]
If u have taken it from any website then place it in that folder

**Comment by codebuzzer01** [comment]
@Amit366  Exactly, It calculates time using binary search algo only, first by calculating mid and then as per the result it decides whether to continue with first half or the second half and then again calculates mid and so on

**Comment by codebuzzer01** [comment]
@Amit366  It searches for the time with the range of 0 to 10^8 .

**Comment by Amit366** [comment]
@codebuzzer01 have u taken it from any online platform like codechef or any?

**Comment by codebuzzer01** [comment]
@Amit366 Its from leetcode under searching and sorting algo

**Comment by Amit366** [comment]
@codebuzzer01 then place it under leetcode folder

**Comment by codebuzzer01** [comment]
Ok

**Comment by codebuzzer01** [comment]
@Amit366 I have performed the above changes.

**Pull request merged**
