### PR TITLE
added a rain water problem

### LINKED ISSUE #1994: Rain water problem
There is a famous rain water trapped between buildings . This is a geeksforgeeks problem .
There are 2 methods possible to solve this problem . And this is asked in faang companies too.
### Programming language

- [ ] C
- [ ] C++
- [ ] Java
- [ ] Python

### PR DESCRIPTION
**Pull request by harshit-dugar**
Fixes #1994 
## Type of change

_Please delete options that are not relevant._

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Documentation Update

# Checklist:

- [ ] My code follows the style guidelines(Clean Code) of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have created a helpful and easy to understand `README.md`
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by ravikr126 — CHANGES_REQUESTED** [review]
Remove binary file

**Comment by harshit-dugar** [comment]
@ravikr126 can you please tell how to delete binary file I have created a new commit still it is showing and no delete option is coming

**Comment by harshit-dugar** [comment]
Binary file is not deleting

**Comment by Amit366** [comment]
@harshit-dugar if it is not deleting then send a new PR.

**Pull request closed without merging**
