### PR TITLE
Added Tower of Hanoi

### LINKED ISSUE #206: Tower of Hanoi
I would like to add the code for the Tower of Hanoi problem under LGM SOC'21.

Language: C++
Please assign this issue to me.

### PR DESCRIPTION
**Pull request by nikhil00shinde**
# Description

In this problem, we are given 3 rods that are the source, destination, and temporary. We have to move for src to dest one at a time. 
I have implemented it in Java
Fixes #206 

Replace #206 with the issue number which is fixed in this PR

## Type of change

_Please delete options that are not relevant._

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Review by nikhil00shinde — COMMENTED** [review]
I have added this in Data Structure. Implemented in Java. In this problem, we have iterate over array from both sides in such a way that 2 players have to choose the highest number add in them, and move until they hit a wrong condition.

**Comment by Amit366** [comment]
@nikhil00shinde remove the other file

**Comment by nikhil00shinde** [comment]
> 
> 
> @nikhil00shinde remove the other file



> 
> 
> @nikhil00shinde remove the other file

@Amit366  Which file?

**Comment by nikhil00shinde** [comment]
> 
> 
> @nikhil00shinde remove the other file



@Amit366 Done. I have removed the other file.

**Comment by nikhil00shinde** [comment]
@Amit366 @Ayush7614 Please check it.

**Pull request merged**
