### PR TITLE
challenging cliff (codeforces) problem committed

### LINKED ISSUE #1389: challenging cliffs (problem : 1537C) codeforces
# Aim

- To provide solution for the problem challenging cliffs codeforces in C++

# Details

- This problem is based on greedy algorithms, constructive algorithms , math and implementation
- @ravikr126 @Ayush7614 @Saurabh4626 Please assign me this under LGMSOC21 for C++
### Programming language

- [ ] C
- [ ] C++
- [ ] Java
- [ ] Python

### PR DESCRIPTION
**Pull request by kalash-kala**
# Description

I have provided a solution to the problem "challenging cliffs (1537C)" codeforces
This solution has passed all test cases and was accepted by codeforces

Fixes #1389

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by kalash-kala** [comment]
@ravikr126  please review this PR

**Comment by Amit366** [comment]
@kalash-kala remove other files

**Comment by kalash-kala** [comment]
@Amit366 , @ravikr126  please review this PR , could you check if the extra files have been removed or not, because i have removed them from my side?

**Comment by Amit366** [comment]
@kalash-kala u haven't removed the files

**Comment by Amit366** [comment]
@kalash-kala since there is no update I am closing this.

**Pull request closed without merging**
