### PR TITLE
Created array rotation by K element solution in c++ under Data structure folder for issue #167 assigned to me

### PR DESCRIPTION
**Pull request by archismansaha**
# Description

Please include a summary of the change and which issue is fixed. List any dependencies that are required for this change.

Fixes #(167)

Replace `issue_no` with the issue number which is fixed in this PR

## Type of change
Added the solution of the question "Array Rotation By K elemnt"

_Please delete options that are not relevant._

- [ ] New feature (non-breaking change which adds functionality)

Capture

# Checklist:

- [ ] My code follows the style guidelines(Clean Code) of this 

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have created a helpful and easy to understand `README.md`
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by Amit366** [comment]
@archismansaha please place this file into the Folder from which platform u have taken up this question from

**Comment by archismansaha** [comment]
Ok so after placing into right folder I have to push it and then again have to made a PR??

**Comment by Amit366** [comment]
@archismansaha  ur code has disappeared so do one thing close this PR and again send one. It will be better

**Comment by surajm-333** [comment]
I would like to code this problem in Java. Please assign this issue to me.

**Comment by Amit366** [comment]
@archismansaha remove the exe file

**Comment by archismansaha** [comment]
done @Amit366

**Comment by Amit366** [comment]
@archismansaha but it's still present

**Pull request merged**
