### PR TITLE
Adding the N_Slimes solution in the Atcoder folder

### PR DESCRIPTION
**Pull request by soma2000-lang**
# Description

This is a C++ solution of the problem N-Slimes from  very famous Atcoder Dp Series

Fixes #2077

## Type of change

- [ ] New feature (non-breaking change which adds functionality)
- [ ]  Addition of solution  problem -https://atcoder.jp/contests/dp/tasks/dp_n  in this repo

# Checklist:

- [ ] My code follows the style guidelines(Clean Code) of this project
- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings

### CODE REVIEW

**Comment by soma2000-lang** [comment]
@ravikr126 
Please merge this in the repo

**Comment by ravikr126** [comment]
Remove the second file

**Comment by soma2000-lang** [comment]
@ravikr126 sir
Which 2 nd file are you talking about??
I have just created a  folder then added the C++ solution in that

**Comment by soma2000-lang** [comment]
@ravikr126  done  the needfull

**Review by ravikr126 — APPROVED** [review]

**Pull request merged**
