### PR TITLE
Added Codes in the CodeChef folder

### PR DESCRIPTION
**Pull request by AtigPurohit**
# Description

Please include a summary of the change and which issue is fixed. List any dependencies that are required for this change.

Fixes #(issue_no)

Replace `issue_no` with the issue number which is fixed in this PR

## Type of change

_Please delete options that are not relevant._

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Documentation Update

# Checklist:

- [ ] My code follows the style guidelines(Clean Code) of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have created a helpful and easy to understand `README.md`
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by sameeksharl — COMMENTED** [review]
Could you add questions as well for each of this ? @AtigPurohit

**Comment by AtigPurohit** [comment]
I have added the question links in the beginning of each other and commented them.

**Comment by sameeksharl** [comment]
Okay, will look into it.

**Comment by AtigPurohit** [comment]
Okay

**Comment by Amit366** [comment]
@AtigPurohit mention issue number

**Review by Ayush7614 — COMMENTED** [review]
@AtigPurohit Add your issue no until i am close your PR

**Pull request merged**
