### PR TITLE
Solution of Valid_Mountain_Problem in Python

### LINKED ISSUE #1011: Valid Mountain Array
I would like to add a solution to this question.

Screenshot 2021-06-15 233944

### Language:
C++

### PR DESCRIPTION
**Pull request by apran-vs**
# Description

Please include a summary of the change and which issue is fixed. List any dependencies that are required for this change.

Fixes #1011 

Replace `issue_no` with the issue number which is fixed in this PR

# Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have created a helpful and easy to understand `README.md`
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by Amit366** [comment]
@apran-vs add test cases

**Comment by apran-vs** [comment]
I already add test case
Please recheck

**Comment by Amit366** [comment]
@apran-vs where have u added??

**Comment by apran-vs** [comment]
In the main python file.
I added 4 test case.

**Comment by Amit366** [comment]
@apran-vs are u in slack??

**Comment by Amit366** [comment]
If yes then go through the messages

**Comment by apran-vs** [comment]
Yes but there are many messages.
So can you give some ideas how to add test case??

**Comment by Amit366** [comment]
@apran-vs go through the pinned messages

**Comment by Amit366** [comment]
@apran-vs add main function

**Comment by apran-vs** [comment]
please check updated file

**Comment by Amit366** [comment]
@apran-vs u haven't placed it in a folder. Place it

**Pull request closed without merging**
