### PR TITLE
commit

### PR DESCRIPTION
**Pull request by Ayan-thecodeking**
issue number #247

### CODE REVIEW

**Comment by Ayan-thecodeking** [comment]
added concatenatedword program in C++

**Comment by Amit366** [comment]
@Ayan-thecodeking add the issue number

**Comment by Amit366** [comment]
@Ayan-thecodeking there is no file

**Comment by Ayan-thecodeking** [comment]
> @Ayan-thecodeking there is no file

so s0rry...now please check again

**Pull request merged**
