### PR TITLE
Pascal Triangle.c

### LINKED ISSUE #1244: Pascal Triangle (Leetcode)
I would like to add this question in C++ language.

Screenshot (83)

### PR DESCRIPTION
**Pull request by harshita9621**
# Description

Solve Pascal Triangle in C language.

Fixes #1244 

## Type of change

_Please delete options that are not relevant._

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Documentation Update

# Checklist:

- [ ] My code follows the style guidelines(Clean Code) of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have created a helpful and easy to understand `README.md`
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by Amit366** [comment]
@harshita9621 add test case

**Comment by harshita9621** [comment]
@Amit366 Pascal Triangle get updated kindly review.

**Comment by Amit366** [comment]
@harshita9621 please check #1316 for test case

**Comment by harshita9621** [comment]
Test case is updated

**Pull request merged**
