### PR TITLE
added Longest_valid_parentheses solution

### PR DESCRIPTION
**Pull request by Anuradha0501**
added solution of longest valid Parentheses (Hard-DP, string) in CPP

issue no. #756

### CODE REVIEW

**Comment by Anuradha0501** [comment]
@Ayush7614 @Amit366 review my pr

**Comment by Anuradha0501** [comment]
added java solution for rod cutting problem - DP
fixes #796

**Comment by Amit366** [comment]
@Anuradha0501 remove the other file

**Comment by Anuradha0501** [comment]
> @Anuradha0501 remove the other file

removed

**Pull request merged**
