### PR TITLE
Added shortest supersequence in python

### LINKED ISSUE #1274: Solution of Shortest Common Supersequence of LeetCode
# Aim

- Wants to add the solution of Shortest Common Supersequence of LeetCode

### Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

### PR DESCRIPTION
**Pull request by siddhi-244**
# Description

Added shortest supersequence in python.

Fixes #1274 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have created a helpful and easy to understand `README.md`
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works
Screenshot_20210628-180118_Chrome

### CODE REVIEW

**Comment by Amit366** [comment]
@siddhi-244 this is similar to https://www.geeksforgeeks.org/shortest-common-supersequence/

**Comment by siddhi-244** [comment]
Sir the approach is same but the variables are different @Amit366

**Comment by Amit366** [comment]
@siddhi-244 only one variable is different. So we cannot accept it

**Comment by siddhi-244** [comment]
Ok I will try some other approaches @Amit366

**Pull request closed without merging**
