### PR TITLE
Added the C++ program to evaluate the Length of Highest Mountain

### LINKED ISSUE #177: Length of the  Highest Mountain
# Aim

- To make a program that finds the length of the highest peak in the mountain using C++.

# Details

- The function takes an array of integers as an input and returns the length of the highest peak.

### Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

### PR DESCRIPTION
**Pull request by Debargha-arch**
# Description

Please include a summary of the change and which issue is fixed. List any dependencies that are required for this change.

Fixes #177

Replace `issue_no` with the issue number which is fixed in this PR

## Type of change

_Please delete options that are not relevant._

# Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by Amit366** [comment]
@Debargha-arch please place this file under GFG or hackerrank or leetcode, from which ever platform the question is taken from

**Comment by Debargha-arch** [comment]
This question is from leetcode. 
@Amit366  I have to just change the location of the directory right?

**Comment by Amit366** [comment]
@Debargha-arch yes

**Comment by Amit366** [comment]
@Debargha-arch  add this file to the hackerrank or leetcode from where ever u have taken from

**Comment by Debargha-arch** [comment]
> @Debargha-arch add this file to the hackerrank or leetcode from where ever u have taken from
My new commit should come under this ie. issue #264  .But the commit went under issue #390 .Please suggest me what to do now?

**Comment by Debargha-arch** [comment]
@Amit366 Please review this PR and merge

**Comment by Debargha-arch** [comment]
My PR went under issue #264 which has the same problem statement and is labelled LGM-SOC Level 2.Kindly,check that.

**Comment by Amit366** [comment]
@Debargha-arch please close both the PRs and create a new one

**Comment by Amit366** [comment]
It's becoming tough for us to handle this type of work

**Pull request closed without merging**
