### PR TITLE
clone a linked list with random pointer.cpp

### PR DESCRIPTION
**Pull request by jaya232**
I have solved issue no. #393

A linked list of length n is given such that each node contains an additional random pointer, which could point to any node in the list, or null.
Construct a deep copy of the list. The deep copy should consist of exactly n brand new nodes, where each new node has its value set to the value of its corresponding original node. Both the next and random pointer of the new nodes should point to new nodes in the copied list such that the pointers in the original list and copied list represent the same list state. None of the pointers in the new list should point to nodes in the original list.
Testcase:
Input: head = [[7,null],[13,0],[11,4],[10,2],[1,0]]
Output: [[7,null],[13,0],[11,4],[10,2],[1,0]]

Fixes #issue_no-393

### CODE REVIEW

**Comment by Amit366** [comment]
@jaya232 add test case

**Comment by jaya232** [comment]
> 
> 
> @jaya232 add test case

@Amit366 sir I have added the test case now.

**Comment by jaya232** [comment]
> 
> 
> @jaya232 where have u added?? Refer to merged PRs

@Amit366 sir but it is showing open means not merged yet to me.

**Comment by Amit366** [comment]
@jaya232 refer to other PRs which are merged

**Comment by jaya232** [comment]
> 
> 
> @jaya232 refer to other PRs which are merged

@Amit366 sir now i have added test cases.Pls check

**Comment by Amit366** [comment]
@jaya232 place it in a folder

**Comment by jaya232** [comment]
> 
> 
> @jaya232 place it in a folder

@Amit366 sir done pls check.

**Pull request merged**
