### PR TITLE
Sol for sorting an array of 012 in C

### LINKED ISSUE #1768: Sort an array of 0s,1s and 2s
# Aim

Want to add a solution of "Sort an array of 0s,1s and 2s"
Kindly assign me this problem. I would like to add my solution to this problem in C++ easily and efficiently using DNF sorting.
Link to the problem: https://www.geeksforgeeks.org/sort-an-array-of-0s-1s-and-2s/

# Details
Given an array A[] consisting 0s, 1s and 2s. The task is to write a function that sorts the given array. The functions should put all 0s first, then all 1s and all 2s in last.
Examples: 
 
Input: {0, 1, 2, 0, 1, 2}
Output: {0, 0, 1, 1, 2, 2}

Input: {0, 1, 1, 0, 1, 2, 1, 2, 0, 0, 0, 1}
Output: {0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2}

### Programming language

- [ ] C
- [ ] C++
- [ ] Java
- [ ] Python

### PR DESCRIPTION
**Pull request by Vidhi6340**
# Description

solution code in C for sorting an array of 0s,1s and 2s is added in Miscellaneous Problems Folder

Fixes #1768 

Replace `issue_no` with the issue number which is fixed in this PR

## Type of change

_Please delete options that are not relevant._

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Documentation Update

# Checklist:

- [x ] My code follows the style guidelines(Clean Code) of this project
- [x ] I have performed a self-review of my own code
- [x ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have created a helpful and easy to understand `README.md`
- [ ] I have made corresponding changes to the documentation
- [x ] My changes generate no new warnings
- [ ] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by Amit366** [comment]
@Vidhi6340 test cases?

**Comment by Amit366** [comment]
@Vidhi6340 also add the code to proper folder

**Comment by Vidhi6340** [comment]
> @Vidhi6340 test cases?

@Amit366 by test cases u mean I need to take an input T (number of test cases) in the main program and then run the program T times?Could u please clarify this.

**Comment by Amit366** [comment]
@Vidhi6340 checkout other merged PRs

**Pull request merged**
