### PR TITLE
Create rotate90.cpp ❧

### LINKED ISSUE #1874: Rotate Matrix 90 degree
**Is your feature request related to a problem? Please describe.**
For the given matrix, the compiler will rotate the matrix into 90 degree and will give the output sir

**Describe the solution you'd like**
I would like to do it on c++ language sir

### Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

### PR DESCRIPTION
**Pull request by manognyaa**
# Description

For the given matrix, the compiler will rotate the matrix into 90 degree and will give the output sir

Fixes #1874 

Replace `issue_no` with the issue number which is fixed in this PR

## Type of change

_Please delete options that are not relevant._

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Documentation Update

# Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have created a helpful and easy to understand `README.md`
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by Ayush7614** [comment]
Delete Top K question file @manognyaa

**Comment by manognyaa** [comment]
yes sir, sorry for the inconvenience caused. now, i deleted the file, can you pls check again @Ayush7614 sir now.

**Comment by Amit366** [comment]
@manognyaa add test case

**Comment by manognyaa** [comment]
yes sir, I added the test cases sir, please guide me if any changes are required @Amit366 sir.

**Pull request merged**
