### PR TITLE
Adding Doubly-Linked-List2.cpp

### LINKED ISSUE #1700: Bug in a Data Structures program
**Describe the bug**
The file 'Doubly-Linked-List.cpp' under folder 'Data Structures' contains array like indexing using maps but no where it updates the maps after Insertions or Deletions making the map useless after some operation

**To Reproduce**
1. Go to 'Data\ Structures/ Doubly-Linked-List.cpp 
2. Run the Program
3. Insert a few nodes linearly then print the lists and then again insert Nodes Randomly this time and print again.

### Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

**Expected behavior**
It should be able to update the map after appropriate insertions and deletions.

### PR DESCRIPTION
**Pull request by pratyush-kr**
# Description

Created a function updateMap to keep check of the map after every relevant insertions and deletions

Fixes #1700  

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

# Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I have added screenshots that prove my fix is effective or that my feature works

# Screenshot

### CODE REVIEW

**Comment by pratyush-kr** [comment]
@chicken-biryani please merge this...

**Comment by Amit366** [comment]
@pratyush-kr add test case

**Comment by Amit366** [comment]
@pratyush-kr where is test case?

**Comment by pratyush-kr** [comment]
@Amit366 I have added the test cases now

**Comment by pratyush-kr** [comment]
Test Case: insertAtHead 1 insertAtTail 2 insertAtTail 3 insertAtTail 4 insertAtTail 5 show insertAt 1 9 show insertAtHead 0 show deletePos 2 show deleteHead show deleteTail show deleteTail show deleteHead deleteHead show deleteTail show exit
Output: -
[1]<->[2]<->[3]<->[4]<->[5]
[1]<->[9]<->[2]<->[3]<->[4]<->[5]
[0]<->[1]<->[9]<->[2]<->[3]<->[4]<->[5]
[0]<->[1]<->[2]<->[3]<->[4]<->[5]
[1]<->[2]<->[3]<->[4]<->[5]
[1]<->[2]<->[3]
[3]
[]

**Pull request merged**
