### PR TITLE
Taxi program from code forces in c++

### LINKED ISSUE #1119: Taxi program from codeforces
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
I want to add the solution of taxi problem from code forces.
Problem link-https://codeforces.com/problemset/problem/158/B

### Programming language

- [x] C
- [x] C++
- [x] Java
- [ ] Python
Please assign it to me under lgmsoc @Ayush7614 @Amit366

### PR DESCRIPTION
**Pull request by Khushi-agarwal**
# Description

Please include a summary of the change and which issue is fixed. List any dependencies that are required for this change.

Fixes #1119 

Added code for taxi program in c++ language.

## Type of change

_Please delete options that are not relevant._

- [x] Bug fix (non-breaking change which fixes an issue)

# Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have created a helpful and easy to understand `README.md`
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by ravikr126** [comment]
Someone already raise this issue before you @Khushi-agarwal

**Comment by Khushi-agarwal** [comment]
@ravikr126 this issue was opened by me and I have made the pr in two languages one was c++ and the other one was java.

**Comment by ravikr126** [comment]
Yes I know but I see this issue already present in the repo by someone

**Comment by Khushi-agarwal** [comment]
> Yes I know but I see this issue already present in the repo by someone

Okay @ravikr126 :)

**Comment by ravikr126** [comment]
You cN create another issue @Khushi-agarwal

**Comment by Khushi-agarwal** [comment]
@ravikr126 I have created a issue #1110 in which you had asked about the question.I have mentioned it so if you could kindly look into it.Thanks.

**Pull request closed without merging**
