### PR TITLE
solution for n queens in java

### LINKED ISSUE #672: N Queen Problem in C++
# Aim

- N queen problem using Backtracking Concept.
- Using C++.

### Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

### PR DESCRIPTION
**Pull request by kumarshobhit**
# Description

Please include a summary of the change and which issue is fixed. List any dependencies that are required for this change.

Fixes #672 

Replace `issue_no` with the issue number which is fixed in this PR

## Type of change

_Please delete options that are not relevant._

- [x] New feature (non-breaking change which adds functionality)
- image

# Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have created a helpful and easy to understand `README.md`
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by Amit366** [comment]
@kumarshobhit add test cases

**Comment by kumarshobhit** [comment]
ok noted

**Comment by kumarshobhit** [comment]
I have added the test cases for the problem. Please check.

**Comment by Amit366** [comment]
@kumarshobhit add it like input and output

**Comment by kumarshobhit** [comment]
@Amit366 done.

**Pull request merged**
