### PR TITLE
Create Minimum Dual Area.cpp

### LINKED ISSUE #898: Minimum Dual Distance
**Is your feature request related to a problem? Please describe.**
I want to work on Minimum Dual Distance Question from CodeChef
Question: https://www.codechef.com/JUNE21C/problems/DAREA

**Describe the solution you'd like**
I want to work on it with C++.

I'm from LGM-SOC
**Additional context**

### Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

### PR DESCRIPTION
**Pull request by vanishasamriddhi**
# Description

Please include a summary of the change and which issue is fixed. List any dependencies that are required for this change.

Fixes #898 

Replace `issue_no` with the issue number which is fixed in this PR

## Type of change

_Please delete options that are not relevant._

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Documentation Update

# Checklist:

- [ ] My code follows the style guidelines(Clean Code) of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have created a helpful and easy to understand `README.md`
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by Amit366** [comment]
@vanishasamriddhi add test case

**Comment by vanishasamriddhi** [comment]
@Amit366 I should add the test case in comments (in the code)?

**Comment by Amit366** [comment]
@vanishasamriddhi add it below the code in the form of comments

**Comment by vanishasamriddhi** [comment]
@Amit366 Done, My apologies for the delay.

**Pull request merged**
