### PR TITLE
Added Java-Solution Maximum Length of Repeated Subarray

### LINKED ISSUE #1899: Maximum Length of Repeated Subarray-Python
# Aim

- Provide the python code for Maximum Length of Repeated Subarray-Python

# Details

image

### Programming language

- [ ] C
- [ ] C++
- [ ] Java
- [X ] Python

### PR DESCRIPTION
**Pull request by 2000shivam659**
# Description

Easy Java-Solution for "Maximum Length of Repeated Subarray" using DP. 

Fixes #1899 

Replace #1899  with the issue number which is fixed in this PR

## Type of change

_Please delete options that are not relevant._

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update
- [ ] Documentation Update

# Checklist:

- [ ] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have created a helpful and easy to understand `README.md`
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by 2000shivam659** [comment]
@Amit366 @ravikr126 @Ayush7614
please review my this PR and merge it, I will thankful for you.

**Comment by 2000shivam659** [comment]
@ravikr126 @Ayush7614 Please review this.

**Comment by Amit366** [comment]
@2000shivam659 main function??

**Comment by 2000shivam659** [comment]
@Amit366 @ravikr126 @Ayush7614 Please check it.

**Pull request merged**
