### PR TITLE
Create RomanToInt.py

### LINKED ISSUE #1739: C++ Solution for "Roman to Integer" on LeetCode under LGMSOC21
Problem: "Roman to Integer" on LeetCode
[https://leetcode.com/problems/roman-to-integer/](https://leetcode.com/problems/roman-to-integer/)

image

Would like to add the C++ solution.
@Amit366 @ravikr126 @Ayush7614 

### Programming language

- [ ] C
- [ ] C++
- [ ] Java
- [ ] Python

### PR DESCRIPTION
**Pull request by monishamandal02**
# Description

Please include a summary of the change and which issue is fixed. List any dependencies that are required for this change.

Fixes #1739

Replace `issue_no` with the issue number which is fixed in this PR

## Type of change

_Please delete options that are not relevant._

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Documentation Update

# Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by AtrikGit6174** [comment]
@monishamandal02 please mention the issue number as Fixes #1739. That is the relevant one that you have solved. This will help the mentors.

**Comment by monishamandal02** [comment]
Done 😊

**Comment by Amit366** [comment]
@monishamandal02 u haven't commented in the issue that you wanna try it out. I am accepting this but next time if u r not assigned any issue then ur PR will not be accepted.

**Comment by Amit366** [comment]
Also add the main function

**Comment by monishamandal02** [comment]
Oh sorry, I will keep that in mind next time.

**Comment by Amit366** [comment]
@monishamandal02 any updates??

**Comment by monishamandal02** [comment]
Done

**Pull request merged**
