### PR TITLE
Count sort- Algorithms

### LINKED ISSUE #2326: Count Sort- Algorithms
## Desciption:
Count sort code in Algorithm section

## Programming Language
- [x] C++

### PR DESCRIPTION
**Pull request by gunjan-g**
# Description
Code added for Count Sort in C++ 

Fixes #2326 

# Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by gunjan-g** [comment]
@sameeksharl @ravikr126 please review the pr

**Comment by gunjan-g** [comment]
@sameeksharl @ravikr126 please review the pr

**Review by Ayush7614 — APPROVED** [review]
Good Work

**Comment by gunjan-g** [comment]
> Good Work

thank you 😄

**Pull request merged**
