### PR TITLE
Added Solution of  check-if-the-sentence-is-pangram in java under LGMSOC'21

### LINKED ISSUE #1537: Check if Sentence is Pangram (Leetcode) in Java Under LGMSOC'21
# Aim

- Want to add solution for Check if the Sentence is Pangram in Java Under LGMSOC'21.

# Details

- Problem link - https://leetcode.com/problems/check-if-the-sentence-is-pangram/

## Language Used - Java.

@Ayush7614 @ravikr126 please assign me this.
 

### Programming language

- [ ] C
- [ ] C++
- [x] Java
- [ ] Python

### PR DESCRIPTION
**Pull request by rajeshkumar2024**
# Description

Added solution of  check-if-the-sentence-is-pangram (Leetcode) in java with some example test case under LGMSOC'21

Fixes #1537 

Replace `issue_no` with the issue number which is fixed in this PR

## Type of change

_Please delete options that are not relevant._

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by Amit366** [comment]
@rajeshkumar2024 main function??

**Comment by rajeshkumar2024** [comment]
@Amit366  In leetcode we get only solution class to solve. That's why i have attached only Solution class.

**Comment by rajeshkumar2024** [comment]
@Amit366 I have added the Main Function please check.

**Comment by Amit366** [comment]
@rajeshkumar2024 in the file itself there are conflicts. I would suggest send another PR.

**Comment by rajeshkumar2024** [comment]
@Amit366 ok sir I will raise another PR.

**Pull request closed without merging**
