### PR TITLE
dice tower codeforces #1213

### PR DESCRIPTION
**Pull request by ChetasShree**
## Type of change
- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by Amit366** [comment]
@ChetasShree mention issue number

**Comment by ChetasShree** [comment]
Dice Tower question on Codeforces  -> #1213
Mountain Scenery question on Codeforces -> #1295
@Amit366

**Comment by Amit366** [comment]
@ChetasShree make separate PRs for each

**Comment by ChetasShree** [comment]
@Amit366 ,how to do that?

**Comment by Amit366** [comment]
@ChetasShree like u sent this PR similar send PRs containing one file for each Issue.

**Comment by ChetasShree** [comment]
@Amit366 ,Thank you sir ,I made separate PRs .

**Pull request closed without merging**
