### PR TITLE
Added disjoint set application in python

### LINKED ISSUE #548: Disjoint set application problem
# Aim

Consider a situation with a number of persons and following tasks to be performed on them.

Add a new friendship relation, i.e., a person x becomes friend of another person y.
Find whether individual x is a friend of individual y (direct or indirect friend)

### Programming language

- [ ] C
- [ ] C++
- [ ] Java
- [ ] Python

### PR DESCRIPTION
**Pull request by girija0707**
# Description

Added disjoint set in python

Fixes #548 

## Type of change
- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have created a helpful and easy to understand `README.md`
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by Amit366** [comment]
@girija0707 add test case

**Comment by girija0707** [comment]
@Amit366 I've added the test case

**Comment by Amit366** [comment]
@girija0707 remove the white spaces

**Comment by girija0707** [comment]
@Amit366 I have done the suggested changes

**Comment by Amit366** [comment]
@girija0707 it is same as https://leetcode.com/problems/number-of-provinces/discuss/1318471/python-union-find-answer. If you want send another PR without plagiarism.

**Comment by girija0707** [comment]
ok I will make another PR

**Pull request closed without merging**
