### PR TITLE
maximum rectangular area in histogram.cpp

### PR DESCRIPTION
**Pull request by jaya232**
i have solved this problem in c++.

Ques: Find the largest rectangular area possible in a given histogram where the largest rectangle can be made of a number of contiguous bars. For simplicity, assume that all bars have the same width and the width is 1 unit.

Fixes #issue no. #237

### CODE REVIEW

**Comment by Amit366** [comment]
@jaya232 add the cpp extension

**Comment by jaya232** [comment]
> 
> 
> @jaya232 add the cpp extension

@Amit366 sir I have added the extension,please check.

**Comment by Amit366** [comment]
where is the extension ?? @jaya232

**Comment by Amit366** [comment]
@jaya232 why two files?? Delete the other file and do the changes suggested yesterday

**Comment by jaya232** [comment]
> 
> 
> @jaya232 why two files?? Delete the other file and do the changes suggested yesterday

@Amit366 sir there is some problem i had commited this file separately but it gets merged with this and delete option is also not working for that file  so should I close this pull request and do a new pull request for "maximum rectangular area in histogram".

**Comment by Amit366** [comment]
@jaya232 yes.

**Pull request closed without merging**
