### PR TITLE
Code added for First Neg number of window of size k

### LINKED ISSUE #1459: First negative integer in every window of size k (GFG)
# Aim

Screenshot 2021-06-26 030022

# Details

- I want to solve this question in C++ language using the sliding window technique.

### Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

### PR DESCRIPTION
**Pull request by Sanskriti2401**
# Description

Code added for First Neg number of window of size k (GFG problem) in C++

Fixes #1459 

# Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by Sanskriti2401** [comment]
@ravikr126 @Ayush7614  , Kindly review my code under LGMSOC'21

**Comment by ravikr126** [comment]
Remove .exe file @Sanskriti2401

**Review by ravikr126 — CHANGES_REQUESTED** [review]
Remove .Exe file

**Comment by Sanskriti2401** [comment]
@ravikr126 The file is already removed and it's not mine. I don't know how it came.

**Comment by ravikr126** [comment]
But this pr is created by you so check the folder I this there is exe file also .
Check the hidden files also @Sanskriti2401

**Review by ravikr126 — APPROVED** [review]

**Review by ravikr126 — APPROVED** [review]

**Pull request merged**
