### PR TITLE
Create Longest_valid_parentheses.cpp

### PR DESCRIPTION
**Pull request by Anuradha0501**
added solution of longest valid Parentheses (Hard-DP, string) in CPP 

issue no. #756

### CODE REVIEW

**Comment by Amit366** [comment]
@Anuradha0501 add main function

**Comment by Anuradha0501** [comment]
ok

**Comment by Anuradha0501** [comment]
> @Anuradha0501 add main function

Main function is added

**Comment by Anuradha0501** [comment]
> @Anuradha0501 add main function

Main function is added

**Comment by Amit366** [comment]
@Anuradha0501 check the folder in which u have placed ur code

**Comment by Anuradha0501** [comment]
ok i will again create pr for this issue.
There are some problem in my repository so i am closing this pr and creating it again.

**Pull request closed without merging**
