### PR TITLE
Maps-STL HackerRank

### LINKED ISSUE #2016: Maps-STL HackerRank
**Program Link:**
https://www.hackerrank.com/challenges/cpp-maps/problem

**Aim:**
You are appointed as the assistant to a teacher in a school and she is correcting the answer sheets of the students. Each student can have multiple answer sheets. So the teacher has Q queries:

1. X Y : Add the marks Y to the student whose name is X.
2. X : Erase the marks of the students whose name is X.
3. X : Print the marks of the students whose name is X. (If X didn't get any marks print  0.)

**Details:**
image

**Programming Languages:**
- [x] C++
- [ ] C
- [ ] Java
- [ ] Python

### PR DESCRIPTION
**Pull request by gunjan-g**
# Description
Code added for Maps-STL in C++

Fixes #2016 

# Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by gunjan-g** [comment]
@ravikr126

**Review by ravikr126 — CHANGES_REQUESTED** [review]
Add testcases

**Comment by gunjan-g** [comment]
> Add testcases

@ravikr126  Could you please tell or refer to a commit so that I can know how to add testcases

**Comment by gunjan-g** [comment]
@ravikr126 Added testcase

**Review by ravikr126 — APPROVED** [review]

**Pull request merged**
