### PR TITLE
Added Cpp Solution to Majority Element

### LINKED ISSUE #1618: Majority Element(Leetcode)
## AIM
I will be adding a question in the Leetcode folder [Majority Element](https://leetcode.com/problems/majority-element/).

-  Given an array nums of size n, return the majority element.
The majority element is the element that appears more than ⌊n / 2⌋ times. You may assume that the majority element always exists in the array.

> Test Cases:-

Input: nums = [3,2,3]
Output: 3
Input: nums = [2,2,1,1,1,2,2]
Output: 2

Please Assign me this issue @Amit366  @ravikr126  @Saurabh4626 
### Programming language

- [ ] C
- [ ] C++
- [ ] Java
- [ ] Python

### PR DESCRIPTION
**Pull request by codingninja11**
# Description

Added a function to solve the majority element problem where the array is sorted first and then the index at n/2 is returned.

Fixes #1618  
_Please delete options that are not relevant._

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Documentation Update

# Checklist:

- [ ] My code follows the style guidelines(Clean Code) of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have created a helpful and easy to understand `README.md`
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by codingninja11** [comment]
@Ayush7614 Please review it.

**Review by ravikr126 — APPROVED** [review]

**Comment by ravikr126** [comment]
Why your id name @codingninja11 🤔

**Comment by anushruti11** [comment]
> Why your id name @codingninja11 🤔

Just a matter of choice :)

**Comment by codingninja11** [comment]
> Why your id name @codingninja11 🤔

Just a matter of choice :)

**Pull request merged**
