### PR TITLE
Added Bubble sort algo in this folder

### LINKED ISSUE #216: Want to add bubble sort question in CPP

### PR DESCRIPTION
**Pull request by mitali-1703**
# Description

I have added Bubble Sort algorithm with proper implementation in CPP which wasn't there before.

Fixes #216 

## Type of change

_Please delete options that are not relevant._

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update
- [x] Documentation Update

# Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by Amit366** [comment]
@mitali-1703 remove the other files

**Comment by mitali-1703** [comment]
> @mitali-1703 remove the other files

Removed @Amit366

**Comment by kamleshjoshi8102** [comment]
@Amit366  : P

https://www.tutorialspoint.com/cplusplus-program-to-implement-bubble-sort

**Comment by Amit366** [comment]
@mitali this is similar to the above link

**Pull request merged**
