### PR TITLE
Lapindromes problems of codechef in java added

### PR DESCRIPTION
**Pull request by viki4545**
# Lapindromes problems of codechef in java added

Please include a summary of the change and which issue is fixed. List any dependencies that are required for this change.

Fixes #1446

Replace `issue_no` with the issue number which is fixed in this PR

## -Lapindromes problems in java added by two approach
         1.two counter array approach.
         2.one counter array approach(efficient solution with less time complexity)

_Please delete options that are not relevant._

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have created a helpful and easy to understand `README.md`
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by Amit366** [comment]
@viki4545 remove other files

**Comment by viki4545** [comment]
Removed 👍

**Comment by Amit366** [comment]
@viki4545 still present

**Comment by viki4545** [comment]
@Amit366 there is two solution by two different method that is why it is having two files

**Comment by Amit366** [comment]
@viki4545 there are 5 files

**Comment by viki4545** [comment]
Hey @Amit366 now there are only two files in this

**Pull request closed without merging**
