### PR TITLE
Added solution of Unclucky Ticket in codeforces

### LINKED ISSUE #1250: Unlucky Ticket of Codeforces
Want to add the solution of this codeforces question "Unlucky Ticket",
The ques code for this is 160 - B in codeforce.

### Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

### PR DESCRIPTION
**Pull request by akash435**
# Description
Added the solution of codeforces question "Unlucky Ticket"
It is level B question
The question code is 160 - B.

Fixes #1250

## Type of change

_Please delete options that are not relevant._

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Documentation Update

# Checklist:

- [x] My code follows the style guidelines(Clean Code) of this project
- [ ] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have created a helpful and easy to understand `README.md`
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

Below is the screenshot of the output for a given input,

### CODE REVIEW

**Comment by akash435** [comment]
Created a pr for adding solution of "Unlucky Ticket" question in codeforces, please check it.

**Comment by akash435** [comment]
Can you please also check my previous issue, #847 and #1149, are not assigned to me, so if possible please assign then to me.

**Comment by Amit366** [comment]
@akash435 add test case

**Comment by akash435** [comment]
means i need to add more test cases and its solution, is this?

**Comment by Amit366** [comment]
you haven't added any test case. Refer other merged pr

**Pull request closed without merging**
